// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'icon_pack_catalog_api/types.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Normalize a user-provided pack name into a stable catalog key.
String normalizePackKey({required String value}) => RustLib.instance.api
    .crateApiIconPackCatalogApiNormalizePackKey(value: value);

/// Normalize an icon-relative path before generating the catalog key.
String normalizeIconPathWithoutExtension({required String value}) => RustLib
    .instance
    .api
    .crateApiIconPackCatalogApiNormalizeIconPathWithoutExtension(value: value);

/// List all imported icon packs.
Future<List<FrbIconPackSummary>> listPacks({required String rootPath}) =>
    RustLib.instance.api.crateApiIconPackCatalogApiListPacks(
      rootPath: rootPath,
    );

/// Delete an imported icon pack by its catalog key.
Future<void> deletePack({required String rootPath, required String packKey}) =>
    RustLib.instance.api.crateApiIconPackCatalogApiDeletePack(
      rootPath: rootPath,
      packKey: packKey,
    );

/// List icon entries, optionally scoped to a single pack and filtered by query.
Future<List<FrbIconPackEntry>> listIcons({
  required String rootPath,
  String? packKey,
  required String query,
  required int offset,
  required int limit,
}) => RustLib.instance.api.crateApiIconPackCatalogApiListIcons(
  rootPath: rootPath,
  packKey: packKey,
  query: query,
  offset: offset,
  limit: limit,
);

/// Read the SVG contents for a catalog icon key.
Future<String?> readSvgByKey({
  required String rootPath,
  required String iconKey,
}) => RustLib.instance.api.crateApiIconPackCatalogApiReadSvgByKey(
  rootPath: rootPath,
  iconKey: iconKey,
);

/// Import a ZIP or 7Z archive and emit progress events while unpacking SVG files.
Stream<FrbIconPackImportEvent> importPack({
  required String rootPath,
  required String archivePath,
  required String displayName,
}) => RustLib.instance.api.crateApiIconPackCatalogApiImportPack(
  rootPath: rootPath,
  archivePath: archivePath,
  displayName: displayName,
);

/// Import a directory containing SVG files and emit progress events while unpacking.
Stream<FrbIconPackImportEvent> importDirectory({
  required String rootPath,
  required String directoryPath,
  required String displayName,
}) => RustLib.instance.api.crateApiIconPackCatalogApiImportDirectory(
  rootPath: rootPath,
  directoryPath: directoryPath,
  displayName: displayName,
);
