// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'icon_pack_catalog_api.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `archive_format_from_path`, `as_str`, `build_archive_candidates`, `build_directory_candidates`, `build_summary_from_fields`, `collect_directory_paths`, `delete_directory_if_exists`, `detect_shared_root`, `ensure_unique_icon_key`, `entry_file_to_bridge`, `format_millis_to_rfc3339`, `import_candidates_internal`, `into_anyhow`, `into_bridge_error`, `list_pack_keys`, `make_output_file_path`, `manifest_to_summary`, `new`, `normalize_archive_path`, `normalize_icon_path_without_extension_impl`, `normalize_pack_key_impl`, `pack_error`, `parse_rfc3339_to_millis`, `prepare_pack_name`, `read_entry_file`, `read_manifest`, `read_svg_text`, `resolve_root_path`, `should_ignore_archive_path`, `strip_shared_root`, `write_entry_file`, `write_manifest_file`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `CatalogError`, `EntryFile`, `IconPackCatalogErrorCode`, `ImportCandidateSource`, `ImportCandidate`, `ManifestFile`, `ResolvedPackName`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

/// Normalize a user-provided pack name into a stable catalog key.
String normalizePackKey({required String value}) => RustLib.instance.api
    .crateApiIconPackCatalogApiNormalizePackKey(value: value);

/// Normalize an icon-relative path before generating the catalog key.
String normalizeIconPathWithoutExtension({required String value}) => RustLib
    .instance
    .api
    .crateApiIconPackCatalogApiNormalizeIconPathWithoutExtension(value: value);

/// List all imported icon packs.
Future<List<FrbIconPackSummary>> listPacks({required String rootPath}) =>
    RustLib.instance.api.crateApiIconPackCatalogApiListPacks(
      rootPath: rootPath,
    );

/// Delete an imported icon pack by its catalog key.
Future<void> deletePack({required String rootPath, required String packKey}) =>
    RustLib.instance.api.crateApiIconPackCatalogApiDeletePack(
      rootPath: rootPath,
      packKey: packKey,
    );

/// List icon entries, optionally scoped to a single pack and filtered by query.
Future<List<FrbIconPackEntry>> listIcons({
  required String rootPath,
  String? packKey,
  required String query,
  required int offset,
  required int limit,
}) => RustLib.instance.api.crateApiIconPackCatalogApiListIcons(
  rootPath: rootPath,
  packKey: packKey,
  query: query,
  offset: offset,
  limit: limit,
);

/// Read the SVG contents for a catalog icon key.
Future<String?> readSvgByKey({
  required String rootPath,
  required String iconKey,
}) => RustLib.instance.api.crateApiIconPackCatalogApiReadSvgByKey(
  rootPath: rootPath,
  iconKey: iconKey,
);

/// Import a ZIP or 7Z archive and emit progress events while unpacking SVG files.
Stream<FrbIconPackImportEvent> importPack({
  required String rootPath,
  required String archivePath,
  required String displayName,
}) => RustLib.instance.api.crateApiIconPackCatalogApiImportPack(
  rootPath: rootPath,
  archivePath: archivePath,
  displayName: displayName,
);

/// Import a directory containing SVG files and emit progress events while unpacking.
Stream<FrbIconPackImportEvent> importDirectory({
  required String rootPath,
  required String directoryPath,
  required String displayName,
}) => RustLib.instance.api.crateApiIconPackCatalogApiImportDirectory(
  rootPath: rootPath,
  directoryPath: directoryPath,
  displayName: displayName,
);

class FrbIconPackEntry {
  final String key;
  final String packKey;
  final String packName;
  final String iconKey;
  final String name;
  final String relativePath;
  final String svgPath;
  final PlatformInt64 importedAtMillis;

  const FrbIconPackEntry({
    required this.key,
    required this.packKey,
    required this.packName,
    required this.iconKey,
    required this.name,
    required this.relativePath,
    required this.svgPath,
    required this.importedAtMillis,
  });

  @override
  int get hashCode =>
      key.hashCode ^
      packKey.hashCode ^
      packName.hashCode ^
      iconKey.hashCode ^
      name.hashCode ^
      relativePath.hashCode ^
      svgPath.hashCode ^
      importedAtMillis.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FrbIconPackEntry &&
          runtimeType == other.runtimeType &&
          key == other.key &&
          packKey == other.packKey &&
          packName == other.packName &&
          iconKey == other.iconKey &&
          name == other.name &&
          relativePath == other.relativePath &&
          svgPath == other.svgPath &&
          importedAtMillis == other.importedAtMillis;
}

class FrbIconPackError {
  final String code;
  final String message;

  const FrbIconPackError({required this.code, required this.message});

  @override
  int get hashCode => code.hashCode ^ message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FrbIconPackError &&
          runtimeType == other.runtimeType &&
          code == other.code &&
          message == other.message;
}

@freezed
sealed class FrbIconPackImportEvent with _$FrbIconPackImportEvent {
  const FrbIconPackImportEvent._();

  const factory FrbIconPackImportEvent.progress(
    FrbIconPackImportProgress field0,
  ) = FrbIconPackImportEvent_Progress;
  const factory FrbIconPackImportEvent.done(FrbIconPackSummary field0) =
      FrbIconPackImportEvent_Done;
  const factory FrbIconPackImportEvent.error(FrbIconPackError field0) =
      FrbIconPackImportEvent_Error;
}

class FrbIconPackImportProgress {
  final int current;
  final int total;
  final String currentFile;

  const FrbIconPackImportProgress({
    required this.current,
    required this.total,
    required this.currentFile,
  });

  @override
  int get hashCode => current.hashCode ^ total.hashCode ^ currentFile.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FrbIconPackImportProgress &&
          runtimeType == other.runtimeType &&
          current == other.current &&
          total == other.total &&
          currentFile == other.currentFile;
}

class FrbIconPackSummary {
  final String packKey;
  final String displayName;
  final String sourceArchiveName;
  final PlatformInt64 importedAtMillis;
  final int iconCount;

  const FrbIconPackSummary({
    required this.packKey,
    required this.displayName,
    required this.sourceArchiveName,
    required this.importedAtMillis,
    required this.iconCount,
  });

  @override
  int get hashCode =>
      packKey.hashCode ^
      displayName.hashCode ^
      sourceArchiveName.hashCode ^
      importedAtMillis.hashCode ^
      iconCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FrbIconPackSummary &&
          runtimeType == other.runtimeType &&
          packKey == other.packKey &&
          displayName == other.displayName &&
          sourceArchiveName == other.sourceArchiveName &&
          importedAtMillis == other.importedAtMillis &&
          iconCount == other.iconCount;
}
