// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'keepass_api/types.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Open a KeePass database and export it into a normalized structure.
///
/// The result is intentionally storage-oriented:
/// - groups are flattened and linked by `parent_uuid`
/// - entries are flattened and reference their group
/// - every field preserves the `protected` flag
/// - history, attachments and OTP data can be imported without reparsing KDBX
Future<FrbKeepassDatabaseExport> exportKeepassDatabase({
  required FrbKeepassExportOptions opts,
}) => RustLib.instance.api.crateApiKeepassApiExportKeepassDatabase(opts: opts);
