// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `build_database_key`, `export_attachments`, `export_autotype_association`, `export_autotype`, `export_compression`, `export_config`, `export_custom_data_item`, `export_custom_data_map`, `export_database_version`, `export_entry`, `export_fields`, `export_history_entry`, `export_inner_cipher`, `export_keepass_database_blocking`, `export_meta`, `export_otp`, `export_outer_cipher`, `export_times`, `flatten_group`, `format_time`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

/// Open a KeePass database and export it into a normalized structure.
///
/// The result is intentionally storage-oriented:
/// - groups are flattened and linked by `parent_uuid`
/// - entries are flattened and reference their group
/// - every field preserves the `protected` flag
/// - history, attachments and OTP data can be imported without reparsing KDBX
Future<FrbKeepassDatabaseExport> exportKeepassDatabase({
  required FrbKeepassExportOptions opts,
}) => RustLib.instance.api.crateApiKeepassApiExportKeepassDatabase(opts: opts);

class FrbKeepassAttachment {
  final String key;
  final BigInt size;
  final bool protected;
  final Uint8List data;

  const FrbKeepassAttachment({
    required this.key,
    required this.size,
    required this.protected,
    required this.data,
  });

  @override
  int get hashCode =>
      key.hashCode ^ size.hashCode ^ protected.hashCode ^ data.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FrbKeepassAttachment &&
          runtimeType == other.runtimeType &&
          key == other.key &&
          size == other.size &&
          protected == other.protected &&
          data == other.data;
}

class FrbKeepassAutoType {
  final bool enabled;
  final String? defaultSequence;
  final bool? dataTransferObfuscation;
  final List<FrbKeepassAutoTypeAssociation> associations;

  const FrbKeepassAutoType({
    required this.enabled,
    this.defaultSequence,
    this.dataTransferObfuscation,
    required this.associations,
  });

  @override
  int get hashCode =>
      enabled.hashCode ^
      defaultSequence.hashCode ^
      dataTransferObfuscation.hashCode ^
      associations.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FrbKeepassAutoType &&
          runtimeType == other.runtimeType &&
          enabled == other.enabled &&
          defaultSequence == other.defaultSequence &&
          dataTransferObfuscation == other.dataTransferObfuscation &&
          associations == other.associations;
}

class FrbKeepassAutoTypeAssociation {
  final String window;
  final String sequence;

  const FrbKeepassAutoTypeAssociation({
    required this.window,
    required this.sequence,
  });

  @override
  int get hashCode => window.hashCode ^ sequence.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FrbKeepassAutoTypeAssociation &&
          runtimeType == other.runtimeType &&
          window == other.window &&
          sequence == other.sequence;
}

class FrbKeepassConfig {
  final String databaseVersion;
  final String outerCipher;
  final String innerCipher;
  final String compression;
  final String kdfName;
  final String kdfDescription;

  const FrbKeepassConfig({
    required this.databaseVersion,
    required this.outerCipher,
    required this.innerCipher,
    required this.compression,
    required this.kdfName,
    required this.kdfDescription,
  });

  @override
  int get hashCode =>
      databaseVersion.hashCode ^
      outerCipher.hashCode ^
      innerCipher.hashCode ^
      compression.hashCode ^
      kdfName.hashCode ^
      kdfDescription.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FrbKeepassConfig &&
          runtimeType == other.runtimeType &&
          databaseVersion == other.databaseVersion &&
          outerCipher == other.outerCipher &&
          innerCipher == other.innerCipher &&
          compression == other.compression &&
          kdfName == other.kdfName &&
          kdfDescription == other.kdfDescription;
}

class FrbKeepassCustomDataItem {
  final String key;
  final String valueKind;
  final String? stringValue;
  final Uint8List? binaryValue;
  final String? lastModificationTime;

  const FrbKeepassCustomDataItem({
    required this.key,
    required this.valueKind,
    this.stringValue,
    this.binaryValue,
    this.lastModificationTime,
  });

  @override
  int get hashCode =>
      key.hashCode ^
      valueKind.hashCode ^
      stringValue.hashCode ^
      binaryValue.hashCode ^
      lastModificationTime.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FrbKeepassCustomDataItem &&
          runtimeType == other.runtimeType &&
          key == other.key &&
          valueKind == other.valueKind &&
          stringValue == other.stringValue &&
          binaryValue == other.binaryValue &&
          lastModificationTime == other.lastModificationTime;
}

/// Fully normalized KeePass export that preserves most information needed for
/// later import into the application storage.
class FrbKeepassDatabaseExport {
  final String sourcePath;
  final FrbKeepassConfig config;
  final FrbKeepassMeta meta;
  final String rootGroupUuid;
  final List<FrbKeepassGroup> groups;
  final List<FrbKeepassEntry> entries;
  final List<FrbKeepassDeletedObject> deletedObjects;

  const FrbKeepassDatabaseExport({
    required this.sourcePath,
    required this.config,
    required this.meta,
    required this.rootGroupUuid,
    required this.groups,
    required this.entries,
    required this.deletedObjects,
  });

  @override
  int get hashCode =>
      sourcePath.hashCode ^
      config.hashCode ^
      meta.hashCode ^
      rootGroupUuid.hashCode ^
      groups.hashCode ^
      entries.hashCode ^
      deletedObjects.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FrbKeepassDatabaseExport &&
          runtimeType == other.runtimeType &&
          sourcePath == other.sourcePath &&
          config == other.config &&
          meta == other.meta &&
          rootGroupUuid == other.rootGroupUuid &&
          groups == other.groups &&
          entries == other.entries &&
          deletedObjects == other.deletedObjects;
}

class FrbKeepassDeletedObject {
  final String uuid;
  final String? deletionTime;

  const FrbKeepassDeletedObject({required this.uuid, this.deletionTime});

  @override
  int get hashCode => uuid.hashCode ^ deletionTime.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FrbKeepassDeletedObject &&
          runtimeType == other.runtimeType &&
          uuid == other.uuid &&
          deletionTime == other.deletionTime;
}

class FrbKeepassEntry {
  final String uuid;
  final String groupUuid;

  /// Group path relative to the synthetic KeePass root group.
  final String groupPath;
  final String? title;
  final String? username;
  final String? password;
  final String? url;
  final String? notes;
  final List<String> tags;
  final List<FrbKeepassField> fields;
  final FrbKeepassTimes times;
  final List<FrbKeepassCustomDataItem> customData;
  final int? iconId;
  final String? customIconUuid;
  final Uint8List? customIconData;
  final String? foregroundColor;
  final String? backgroundColor;
  final String? overrideUrl;
  final bool? qualityCheck;
  final List<FrbKeepassAttachment> attachments;
  final FrbKeepassAutoType? autotype;
  final FrbKeepassOtp? otp;
  final List<FrbKeepassHistoryEntry> history;

  const FrbKeepassEntry({
    required this.uuid,
    required this.groupUuid,
    required this.groupPath,
    this.title,
    this.username,
    this.password,
    this.url,
    this.notes,
    required this.tags,
    required this.fields,
    required this.times,
    required this.customData,
    this.iconId,
    this.customIconUuid,
    this.customIconData,
    this.foregroundColor,
    this.backgroundColor,
    this.overrideUrl,
    this.qualityCheck,
    required this.attachments,
    this.autotype,
    this.otp,
    required this.history,
  });

  @override
  int get hashCode =>
      uuid.hashCode ^
      groupUuid.hashCode ^
      groupPath.hashCode ^
      title.hashCode ^
      username.hashCode ^
      password.hashCode ^
      url.hashCode ^
      notes.hashCode ^
      tags.hashCode ^
      fields.hashCode ^
      times.hashCode ^
      customData.hashCode ^
      iconId.hashCode ^
      customIconUuid.hashCode ^
      customIconData.hashCode ^
      foregroundColor.hashCode ^
      backgroundColor.hashCode ^
      overrideUrl.hashCode ^
      qualityCheck.hashCode ^
      attachments.hashCode ^
      autotype.hashCode ^
      otp.hashCode ^
      history.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FrbKeepassEntry &&
          runtimeType == other.runtimeType &&
          uuid == other.uuid &&
          groupUuid == other.groupUuid &&
          groupPath == other.groupPath &&
          title == other.title &&
          username == other.username &&
          password == other.password &&
          url == other.url &&
          notes == other.notes &&
          tags == other.tags &&
          fields == other.fields &&
          times == other.times &&
          customData == other.customData &&
          iconId == other.iconId &&
          customIconUuid == other.customIconUuid &&
          customIconData == other.customIconData &&
          foregroundColor == other.foregroundColor &&
          backgroundColor == other.backgroundColor &&
          overrideUrl == other.overrideUrl &&
          qualityCheck == other.qualityCheck &&
          attachments == other.attachments &&
          autotype == other.autotype &&
          otp == other.otp &&
          history == other.history;
}

/// Options for exporting a KeePass database into a normalized structure that is
/// convenient to import into the app storage layer.
class FrbKeepassExportOptions {
  /// Path to the KeePass database (`.kdbx` / `.kdb`).
  final String inputPath;

  /// Optional database password. Keep empty if the database uses only a keyfile.
  final String? password;

  /// Optional path to the KeePass keyfile.
  final String? keyfilePath;

  /// Include entry history snapshots.
  final bool includeHistory;

  /// Include attachment bytes in the export.
  final bool includeAttachments;

  const FrbKeepassExportOptions({
    required this.inputPath,
    this.password,
    this.keyfilePath,
    required this.includeHistory,
    required this.includeAttachments,
  });

  static Future<FrbKeepassExportOptions> simple({
    required String inputPath,
    required String password,
  }) => RustLib.instance.api.crateApiKeepassApiFrbKeepassExportOptionsSimple(
    inputPath: inputPath,
    password: password,
  );

  @override
  int get hashCode =>
      inputPath.hashCode ^
      password.hashCode ^
      keyfilePath.hashCode ^
      includeHistory.hashCode ^
      includeAttachments.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FrbKeepassExportOptions &&
          runtimeType == other.runtimeType &&
          inputPath == other.inputPath &&
          password == other.password &&
          keyfilePath == other.keyfilePath &&
          includeHistory == other.includeHistory &&
          includeAttachments == other.includeAttachments;
}

class FrbKeepassField {
  final String key;
  final String value;
  final bool protected;

  const FrbKeepassField({
    required this.key,
    required this.value,
    required this.protected,
  });

  @override
  int get hashCode => key.hashCode ^ value.hashCode ^ protected.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FrbKeepassField &&
          runtimeType == other.runtimeType &&
          key == other.key &&
          value == other.value &&
          protected == other.protected;
}

class FrbKeepassGroup {
  final String uuid;
  final String? parentUuid;
  final bool isRoot;

  /// Path relative to the synthetic KeePass root group.
  final String path;
  final String name;
  final String? notes;
  final int? iconId;
  final String? customIconUuid;
  final FrbKeepassTimes times;
  final List<FrbKeepassCustomDataItem> customData;
  final bool isExpanded;
  final String? defaultAutotypeSequence;
  final bool? enableAutotype;
  final bool? enableSearching;
  final String? lastTopVisibleEntry;

  const FrbKeepassGroup({
    required this.uuid,
    this.parentUuid,
    required this.isRoot,
    required this.path,
    required this.name,
    this.notes,
    this.iconId,
    this.customIconUuid,
    required this.times,
    required this.customData,
    required this.isExpanded,
    this.defaultAutotypeSequence,
    this.enableAutotype,
    this.enableSearching,
    this.lastTopVisibleEntry,
  });

  @override
  int get hashCode =>
      uuid.hashCode ^
      parentUuid.hashCode ^
      isRoot.hashCode ^
      path.hashCode ^
      name.hashCode ^
      notes.hashCode ^
      iconId.hashCode ^
      customIconUuid.hashCode ^
      times.hashCode ^
      customData.hashCode ^
      isExpanded.hashCode ^
      defaultAutotypeSequence.hashCode ^
      enableAutotype.hashCode ^
      enableSearching.hashCode ^
      lastTopVisibleEntry.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FrbKeepassGroup &&
          runtimeType == other.runtimeType &&
          uuid == other.uuid &&
          parentUuid == other.parentUuid &&
          isRoot == other.isRoot &&
          path == other.path &&
          name == other.name &&
          notes == other.notes &&
          iconId == other.iconId &&
          customIconUuid == other.customIconUuid &&
          times == other.times &&
          customData == other.customData &&
          isExpanded == other.isExpanded &&
          defaultAutotypeSequence == other.defaultAutotypeSequence &&
          enableAutotype == other.enableAutotype &&
          enableSearching == other.enableSearching &&
          lastTopVisibleEntry == other.lastTopVisibleEntry;
}

class FrbKeepassHistoryEntry {
  final String uuid;
  final String? title;
  final String? username;
  final String? password;
  final String? url;
  final String? notes;
  final List<String> tags;
  final List<FrbKeepassField> fields;
  final FrbKeepassTimes times;
  final List<FrbKeepassCustomDataItem> customData;
  final int? iconId;
  final String? customIconUuid;
  final Uint8List? customIconData;
  final String? foregroundColor;
  final String? backgroundColor;
  final String? overrideUrl;
  final bool? qualityCheck;
  final List<FrbKeepassAttachment> attachments;
  final FrbKeepassAutoType? autotype;
  final FrbKeepassOtp? otp;

  const FrbKeepassHistoryEntry({
    required this.uuid,
    this.title,
    this.username,
    this.password,
    this.url,
    this.notes,
    required this.tags,
    required this.fields,
    required this.times,
    required this.customData,
    this.iconId,
    this.customIconUuid,
    this.customIconData,
    this.foregroundColor,
    this.backgroundColor,
    this.overrideUrl,
    this.qualityCheck,
    required this.attachments,
    this.autotype,
    this.otp,
  });

  @override
  int get hashCode =>
      uuid.hashCode ^
      title.hashCode ^
      username.hashCode ^
      password.hashCode ^
      url.hashCode ^
      notes.hashCode ^
      tags.hashCode ^
      fields.hashCode ^
      times.hashCode ^
      customData.hashCode ^
      iconId.hashCode ^
      customIconUuid.hashCode ^
      customIconData.hashCode ^
      foregroundColor.hashCode ^
      backgroundColor.hashCode ^
      overrideUrl.hashCode ^
      qualityCheck.hashCode ^
      attachments.hashCode ^
      autotype.hashCode ^
      otp.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FrbKeepassHistoryEntry &&
          runtimeType == other.runtimeType &&
          uuid == other.uuid &&
          title == other.title &&
          username == other.username &&
          password == other.password &&
          url == other.url &&
          notes == other.notes &&
          tags == other.tags &&
          fields == other.fields &&
          times == other.times &&
          customData == other.customData &&
          iconId == other.iconId &&
          customIconUuid == other.customIconUuid &&
          customIconData == other.customIconData &&
          foregroundColor == other.foregroundColor &&
          backgroundColor == other.backgroundColor &&
          overrideUrl == other.overrideUrl &&
          qualityCheck == other.qualityCheck &&
          attachments == other.attachments &&
          autotype == other.autotype &&
          otp == other.otp;
}

class FrbKeepassMemoryProtection {
  final bool protectTitle;
  final bool protectUsername;
  final bool protectPassword;
  final bool protectUrl;
  final bool protectNotes;

  const FrbKeepassMemoryProtection({
    required this.protectTitle,
    required this.protectUsername,
    required this.protectPassword,
    required this.protectUrl,
    required this.protectNotes,
  });

  @override
  int get hashCode =>
      protectTitle.hashCode ^
      protectUsername.hashCode ^
      protectPassword.hashCode ^
      protectUrl.hashCode ^
      protectNotes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FrbKeepassMemoryProtection &&
          runtimeType == other.runtimeType &&
          protectTitle == other.protectTitle &&
          protectUsername == other.protectUsername &&
          protectPassword == other.protectPassword &&
          protectUrl == other.protectUrl &&
          protectNotes == other.protectNotes;
}

class FrbKeepassMeta {
  final String? generator;
  final String? databaseName;
  final String? databaseNameChanged;
  final String? databaseDescription;
  final String? databaseDescriptionChanged;
  final String? defaultUsername;
  final String? defaultUsernameChanged;
  final int? maintenanceHistoryDays;
  final String? color;
  final String? masterKeyChanged;
  final int? masterKeyChangeRec;
  final int? masterKeyChangeForce;
  final FrbKeepassMemoryProtection? memoryProtection;
  final bool? recyclebinEnabled;
  final String? recyclebinUuid;
  final String? recyclebinChanged;
  final String? entryTemplatesGroup;
  final String? entryTemplatesGroupChanged;
  final String? lastSelectedGroup;
  final String? lastTopVisibleGroup;
  final int? historyMaxItems;
  final int? historyMaxSize;
  final String? settingsChanged;
  final List<FrbKeepassCustomDataItem> customData;

  const FrbKeepassMeta({
    this.generator,
    this.databaseName,
    this.databaseNameChanged,
    this.databaseDescription,
    this.databaseDescriptionChanged,
    this.defaultUsername,
    this.defaultUsernameChanged,
    this.maintenanceHistoryDays,
    this.color,
    this.masterKeyChanged,
    this.masterKeyChangeRec,
    this.masterKeyChangeForce,
    this.memoryProtection,
    this.recyclebinEnabled,
    this.recyclebinUuid,
    this.recyclebinChanged,
    this.entryTemplatesGroup,
    this.entryTemplatesGroupChanged,
    this.lastSelectedGroup,
    this.lastTopVisibleGroup,
    this.historyMaxItems,
    this.historyMaxSize,
    this.settingsChanged,
    required this.customData,
  });

  @override
  int get hashCode =>
      generator.hashCode ^
      databaseName.hashCode ^
      databaseNameChanged.hashCode ^
      databaseDescription.hashCode ^
      databaseDescriptionChanged.hashCode ^
      defaultUsername.hashCode ^
      defaultUsernameChanged.hashCode ^
      maintenanceHistoryDays.hashCode ^
      color.hashCode ^
      masterKeyChanged.hashCode ^
      masterKeyChangeRec.hashCode ^
      masterKeyChangeForce.hashCode ^
      memoryProtection.hashCode ^
      recyclebinEnabled.hashCode ^
      recyclebinUuid.hashCode ^
      recyclebinChanged.hashCode ^
      entryTemplatesGroup.hashCode ^
      entryTemplatesGroupChanged.hashCode ^
      lastSelectedGroup.hashCode ^
      lastTopVisibleGroup.hashCode ^
      historyMaxItems.hashCode ^
      historyMaxSize.hashCode ^
      settingsChanged.hashCode ^
      customData.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FrbKeepassMeta &&
          runtimeType == other.runtimeType &&
          generator == other.generator &&
          databaseName == other.databaseName &&
          databaseNameChanged == other.databaseNameChanged &&
          databaseDescription == other.databaseDescription &&
          databaseDescriptionChanged == other.databaseDescriptionChanged &&
          defaultUsername == other.defaultUsername &&
          defaultUsernameChanged == other.defaultUsernameChanged &&
          maintenanceHistoryDays == other.maintenanceHistoryDays &&
          color == other.color &&
          masterKeyChanged == other.masterKeyChanged &&
          masterKeyChangeRec == other.masterKeyChangeRec &&
          masterKeyChangeForce == other.masterKeyChangeForce &&
          memoryProtection == other.memoryProtection &&
          recyclebinEnabled == other.recyclebinEnabled &&
          recyclebinUuid == other.recyclebinUuid &&
          recyclebinChanged == other.recyclebinChanged &&
          entryTemplatesGroup == other.entryTemplatesGroup &&
          entryTemplatesGroupChanged == other.entryTemplatesGroupChanged &&
          lastSelectedGroup == other.lastSelectedGroup &&
          lastTopVisibleGroup == other.lastTopVisibleGroup &&
          historyMaxItems == other.historyMaxItems &&
          historyMaxSize == other.historyMaxSize &&
          settingsChanged == other.settingsChanged &&
          customData == other.customData;
}

class FrbKeepassOtp {
  final String rawValue;
  final String? label;
  final String? issuer;
  final String? secret;
  final BigInt? period;
  final int? digits;
  final String? algorithm;
  final String? parseError;

  const FrbKeepassOtp({
    required this.rawValue,
    this.label,
    this.issuer,
    this.secret,
    this.period,
    this.digits,
    this.algorithm,
    this.parseError,
  });

  @override
  int get hashCode =>
      rawValue.hashCode ^
      label.hashCode ^
      issuer.hashCode ^
      secret.hashCode ^
      period.hashCode ^
      digits.hashCode ^
      algorithm.hashCode ^
      parseError.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FrbKeepassOtp &&
          runtimeType == other.runtimeType &&
          rawValue == other.rawValue &&
          label == other.label &&
          issuer == other.issuer &&
          secret == other.secret &&
          period == other.period &&
          digits == other.digits &&
          algorithm == other.algorithm &&
          parseError == other.parseError;
}

class FrbKeepassTimes {
  final String? creation;
  final String? lastModification;
  final String? lastAccess;
  final String? expiry;
  final String? locationChanged;
  final bool? expires;
  final int? usageCount;

  const FrbKeepassTimes({
    this.creation,
    this.lastModification,
    this.lastAccess,
    this.expiry,
    this.locationChanged,
    this.expires,
    this.usageCount,
  });

  @override
  int get hashCode =>
      creation.hashCode ^
      lastModification.hashCode ^
      lastAccess.hashCode ^
      expiry.hashCode ^
      locationChanged.hashCode ^
      expires.hashCode ^
      usageCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FrbKeepassTimes &&
          runtimeType == other.runtimeType &&
          creation == other.creation &&
          lastModification == other.lastModification &&
          lastAccess == other.lastAccess &&
          expiry == other.expiry &&
          locationChanged == other.locationChanged &&
          expires == other.expires &&
          usageCount == other.usageCount;
}
