name: hoplixi
description: 'Password manager application'
publish_to: 'none'

version: 1.1.0

environment:
  sdk: '^3.11.4'

dependencies:
  flutter:
    sdk: flutter

  flex_color_scheme: ^8.4.0
  package_info_plus: ^9.0.1
  device_info_plus: ^12.4.0
  archive: ^4.0.9
  uuid: ^4.5.3
  crypto: ^3.0.7
  pointycastle: ^4.0.0
  flutter_secure_storage: ^10.0.0
  smooth_page_indicator: ^2.0.1
  synchronized: ^3.4.0
  cupertino_icons: ^1.0.9
  flutter_riverpod: ^3.3.1
  freezed_annotation: ^3.1.0
  json_annotation: ^4.11.0
  drift: ^2.32.1
  google_fonts: ^8.0.2
  font_awesome_flutter: ^11.0.0
  go_router: ^17.2.1
  google_sign_in: ^7.2.0
  toastification: ^3.1.0
  flutter_svg: ^2.2.4
  tray_manager: ^0.5.2
  shared_preferences: ^2.5.5
  hive_ce: ^2.19.3
  hive_ce_flutter: ^2.3.4
  permission_handler: ^12.0.1
  animations: ^2.1.2
  local_auth: ^3.0.1
  image_picker: ^1.2.1
  path: ^1.9.1
  path_provider: ^2.1.5
  file_picker: ^11.0.2
  flutter_dotenv: ^6.0.0
  get_it: ^9.2.1
  flutter_launcher_icons: ^0.14.4
  result_dart: ^2.2.0
  universal_platform: ^1.1.0
  logger: ^2.7.0
  intl: 0.20.2
  window_manager: ^0.5.1
  animated_text_kit: ^4.3.0
  animated_theme_switcher: ^2.0.10
  wolt_modal_sheet: ^0.11.0
  dotted_border: ^3.1.0
  infinite_scroll_pagination: ^5.1.1
  pinput: ^6.0.2
  flutter_colorpicker: ^1.1.0
  image: ^4.8.0
  flutter_expandable_fab: ^2.5.2
  sliver_tools: ^0.2.12
  flutter_resizable_container: ^4.2.0
  flutter_credit_card: ^4.1.0
  flutter_quill: ^11.5.0
  otp: ^3.2.0
  zxing2: ^0.2.4
  image_cropper: ^12.2.0
  mobile_scanner: ^7.2.0
  crop_image: ^1.0.17
  pasteboard: ^0.5.0
  cryptography: ^2.9.0
  mime: ^2.0.0
  open_file: ^3.5.11
  watcher: ^1.2.1
  protobuf: ^4.2.0
  lucide_icons_flutter: ^3.1.12
  flutter_graph_view: ^2.1.0
  flutter_doc_scanner: ^0.0.20
  build_config: ^1.2.0
  rename_app: ^1.6.5
  open_dir: ^0.0.2+1
  args: ^2.7.0
  flutter_webrtc: ^1.4.1
  flutter_single_instance: ^1.7.0
  desktop_multi_window: ^0.3.0
  launch_at_startup: ^0.5.1

  card_scanner:
    path: ./packages/card_scanner
  typed_prefs:
    version: ^1.1.1
    git: https://github.com/vartec-chs/typed_prefs_flutter
  rust_lib_hoplixi:
    path: rust_builder
  flutter_rust_bridge: 2.12.0
  flutter_localizations:
    sdk: flutter

  flutter_lucide: ^1.9.0
  sqlite3: ^3.3.1
  go_transitions: ^0.8.3
  mdns_dart: ^2.2.1
  network_info_plus: ^7.0.0
  web_socket_channel: ^3.0.3
  desktop_drop: ^0.7.0
  flutter_zxing: ^2.2.1
  slang_flutter: ^4.14.0
  slang: ^4.14.0
  connectivity_plus: ^7.1.1
  no_screenshot: ^1.1.0
  flutter_contacts: ^2.0.2
  op_wifi_utils: ^1.4.3
  flutter_appauth: ^12.0.0
  url_launcher: ^6.3.2
  dio: ^5.9.2
  internet_connection_checker_plus: ^2.9.1+2
  intl_phone_number_input: ^0.7.5
  nfc_manager: ^4.2.1

hooks:
  user_defines:
    sqlite3:
      source: sqlite3mc

dev_dependencies:
  flutter_test:
    sdk: flutter

  # integration_test:
  #   sdk: flutter

  flutter_lints: ^6.0.0
  build_runner: ^2.13.1
  json_serializable: ^6.13.0
  drift_dev: ^2.32.1
  freezed: ^3.2.5
  flutter_flavorizr: ^2.4.2
  intl_utils: ^2.8.14
  slang_build_runner: ^4.14.0

flutter:
  uses-material-design: true

  generate: true # Add this line

  assets:
    - assets/logo/
    - .env
flutter_intl:
  enabled: true
