// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

#![allow(
    non_camel_case_types,
    unused,
    non_snake_case,
    clippy::needless_return,
    clippy::redundant_closure_call,
    clippy::redundant_closure,
    clippy::useless_conversion,
    clippy::unit_arg,
    clippy::unused_unit,
    clippy::double_parens,
    clippy::let_and_return,
    clippy::too_many_arguments,
    clippy::match_single_binding,
    clippy::clone_on_copy,
    clippy::let_unit_value,
    clippy::deref_addrof,
    clippy::explicit_auto_deref,
    clippy::borrow_deref_ref,
    clippy::needless_borrow
)]

// Section: imports

use flutter_rust_bridge::for_generated::byteorder::{NativeEndian, ReadBytesExt, WriteBytesExt};
use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
use flutter_rust_bridge::{Handler, IntoIntoDart};

// Section: boilerplate

flutter_rust_bridge::frb_generated_boilerplate!(
    default_stream_sink_codec = SseCodec,
    default_rust_opaque = RustOpaqueMoi,
    default_rust_auto_opaque = RustAutoOpaqueMoi,
);
pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_VERSION: &str = "2.11.1";
pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_CONTENT_HASH: i32 = 117895093;

// Section: executor

flutter_rust_bridge::frb_generated_default_handler!();

// Section: wire_funcs

fn wire__crate__api__logging__create_log_stream_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "create_log_stream",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_sink = <StreamSink<
                crate::api::logging::LogEntry,
                flutter_rust_bridge::for_generated::SseCodec,
            >>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, ()>((move || {
                    let output_ok = Result::<_, ()>::Ok({
                        crate::api::logging::create_log_stream(api_sink);
                    })?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__crypt_api__decrypt_batch_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::SseCodec, _, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "decrypt_batch",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_opts =
                <crate::api::crypt_api::FrbBatchDecryptOptions>::sse_decode(&mut deserializer);
            let api_sink = <StreamSink<
                crate::api::crypt_api::FrbBatchDecryptEvent,
                flutter_rust_bridge::for_generated::SseCodec,
            >>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| async move {
                transform_result_sse::<_, flutter_rust_bridge::for_generated::anyhow::Error>(
                    (move || async move {
                        let output_ok =
                            crate::api::crypt_api::decrypt_batch(api_opts, api_sink).await?;
                        Ok(output_ok)
                    })()
                    .await,
                )
            }
        },
    )
}
fn wire__crate__api__crypt_api__decrypt_file_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::SseCodec, _, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "decrypt_file",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_opts =
                <crate::api::crypt_api::FrbDecryptOptions>::sse_decode(&mut deserializer);
            let api_sink = <StreamSink<
                crate::api::crypt_api::FrbDecryptEvent,
                flutter_rust_bridge::for_generated::SseCodec,
            >>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| async move {
                transform_result_sse::<_, ()>(
                    (move || async move {
                        let output_ok = Result::<_, ()>::Ok({
                            crate::api::crypt_api::decrypt_file(api_opts, api_sink).await;
                        })?;
                        Ok(output_ok)
                    })()
                    .await,
                )
            }
        },
    )
}
fn wire__crate__api__crypt_api__encrypt_batch_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::SseCodec, _, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "encrypt_batch",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_opts =
                <crate::api::crypt_api::FrbBatchEncryptOptions>::sse_decode(&mut deserializer);
            let api_sink = <StreamSink<
                crate::api::crypt_api::FrbBatchEncryptEvent,
                flutter_rust_bridge::for_generated::SseCodec,
            >>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| async move {
                transform_result_sse::<_, flutter_rust_bridge::for_generated::anyhow::Error>(
                    (move || async move {
                        let output_ok =
                            crate::api::crypt_api::encrypt_batch(api_opts, api_sink).await?;
                        Ok(output_ok)
                    })()
                    .await,
                )
            }
        },
    )
}
fn wire__crate__api__crypt_api__encrypt_file_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::SseCodec, _, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "encrypt_file",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_opts =
                <crate::api::crypt_api::FrbEncryptOptions>::sse_decode(&mut deserializer);
            let api_sink = <StreamSink<
                crate::api::crypt_api::FrbEncryptEvent,
                flutter_rust_bridge::for_generated::SseCodec,
            >>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| async move {
                transform_result_sse::<_, ()>(
                    (move || async move {
                        let output_ok = Result::<_, ()>::Ok({
                            crate::api::crypt_api::encrypt_file(api_opts, api_sink).await;
                        })?;
                        Ok(output_ok)
                    })()
                    .await,
                )
            }
        },
    )
}
fn wire__crate__api__crypt_api__frb_decrypt_options_simple_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "frb_decrypt_options_simple",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_input_path = <String>::sse_decode(&mut deserializer);
            let api_output_dir = <String>::sse_decode(&mut deserializer);
            let api_password = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, ()>((move || {
                    let output_ok =
                        Result::<_, ()>::Ok(crate::api::crypt_api::FrbDecryptOptions::simple(
                            api_input_path,
                            api_output_dir,
                            api_password,
                        ))?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__crypt_api__frb_encrypt_options_simple_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "frb_encrypt_options_simple",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_input_path = <String>::sse_decode(&mut deserializer);
            let api_output_dir = <String>::sse_decode(&mut deserializer);
            let api_password = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, ()>((move || {
                    let output_ok =
                        Result::<_, ()>::Ok(crate::api::crypt_api::FrbEncryptOptions::simple(
                            api_input_path,
                            api_output_dir,
                            api_password,
                        ))?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__simple__greet_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "greet",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_name = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let output_ok = Result::<_, ()>::Ok(crate::api::simple::greet(api_name))?;
                Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__simple__init_app_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "init_app",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, ()>((move || {
                    let output_ok = Result::<_, ()>::Ok({
                        crate::api::simple::init_app();
                    })?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__logging__install_rust_log_bridge_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "install_rust_log_bridge",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_level = <i32>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, String>((move || {
                    let output_ok = crate::api::logging::install_rust_log_bridge(api_level)?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__crypt_api__read_encrypted_header_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::SseCodec, _, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "read_encrypted_header",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_input_path = <String>::sse_decode(&mut deserializer);
            let api_password = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| async move {
                transform_result_sse::<_, flutter_rust_bridge::for_generated::anyhow::Error>(
                    (move || async move {
                        let output_ok = crate::api::crypt_api::read_encrypted_header(
                            api_input_path,
                            api_password,
                        )
                        .await?;
                        Ok(output_ok)
                    })()
                    .await,
                )
            }
        },
    )
}
fn wire__crate__api__logging__rust_log_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "rust_log",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_level = <i32>::sse_decode(&mut deserializer);
            let api_tag = <String>::sse_decode(&mut deserializer);
            let api_msg = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, ()>((move || {
                    let output_ok = Result::<_, ()>::Ok({
                        crate::api::logging::rust_log(api_level, api_tag, api_msg);
                    })?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__logging__rust_log_debug_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "rust_log_debug",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_tag = <String>::sse_decode(&mut deserializer);
            let api_msg = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, ()>((move || {
                    let output_ok = Result::<_, ()>::Ok({
                        crate::api::logging::rust_log_debug(api_tag, api_msg);
                    })?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__logging__rust_log_error_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "rust_log_error",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_tag = <String>::sse_decode(&mut deserializer);
            let api_msg = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, ()>((move || {
                    let output_ok = Result::<_, ()>::Ok({
                        crate::api::logging::rust_log_error(api_tag, api_msg);
                    })?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__logging__rust_log_fatal_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "rust_log_fatal",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_tag = <String>::sse_decode(&mut deserializer);
            let api_msg = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, ()>((move || {
                    let output_ok = Result::<_, ()>::Ok({
                        crate::api::logging::rust_log_fatal(api_tag, api_msg);
                    })?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__logging__rust_log_info_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "rust_log_info",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_tag = <String>::sse_decode(&mut deserializer);
            let api_msg = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, ()>((move || {
                    let output_ok = Result::<_, ()>::Ok({
                        crate::api::logging::rust_log_info(api_tag, api_msg);
                    })?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__logging__rust_log_warning_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "rust_log_warning",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_tag = <String>::sse_decode(&mut deserializer);
            let api_msg = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, ()>((move || {
                    let output_ok = Result::<_, ()>::Ok({
                        crate::api::logging::rust_log_warning(api_tag, api_msg);
                    })?;
                    Ok(output_ok)
                })())
            }
        },
    )
}

// Section: dart2rust

impl SseDecode for flutter_rust_bridge::for_generated::anyhow::Error {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <String>::sse_decode(deserializer);
        return flutter_rust_bridge::for_generated::anyhow::anyhow!("{}", inner);
    }
}

impl SseDecode
    for StreamSink<
        crate::api::crypt_api::FrbBatchDecryptEvent,
        flutter_rust_bridge::for_generated::SseCodec,
    >
{
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <String>::sse_decode(deserializer);
        return StreamSink::deserialize(inner);
    }
}

impl SseDecode
    for StreamSink<
        crate::api::crypt_api::FrbBatchEncryptEvent,
        flutter_rust_bridge::for_generated::SseCodec,
    >
{
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <String>::sse_decode(deserializer);
        return StreamSink::deserialize(inner);
    }
}

impl SseDecode
    for StreamSink<
        crate::api::crypt_api::FrbDecryptEvent,
        flutter_rust_bridge::for_generated::SseCodec,
    >
{
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <String>::sse_decode(deserializer);
        return StreamSink::deserialize(inner);
    }
}

impl SseDecode
    for StreamSink<
        crate::api::crypt_api::FrbEncryptEvent,
        flutter_rust_bridge::for_generated::SseCodec,
    >
{
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <String>::sse_decode(deserializer);
        return StreamSink::deserialize(inner);
    }
}

impl SseDecode
    for StreamSink<crate::api::logging::LogEntry, flutter_rust_bridge::for_generated::SseCodec>
{
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <String>::sse_decode(deserializer);
        return StreamSink::deserialize(inner);
    }
}

impl SseDecode for String {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <Vec<u8>>::sse_decode(deserializer);
        return String::from_utf8(inner).unwrap();
    }
}

impl SseDecode for bool {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u8().unwrap() != 0
    }
}

impl SseDecode for f64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_f64::<NativeEndian>().unwrap()
    }
}

impl SseDecode for crate::api::crypt_api::FrbBatchDecryptEvent {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut tag_ = <i32>::sse_decode(deserializer);
        match tag_ {
            0 => {
                let mut var_fileIndex = <u32>::sse_decode(deserializer);
                let mut var_totalFiles = <u32>::sse_decode(deserializer);
                let mut var_currentFile = <String>::sse_decode(deserializer);
                let mut var_progress =
                    <crate::api::crypt_api::FrbProgressEvent>::sse_decode(deserializer);
                return crate::api::crypt_api::FrbBatchDecryptEvent::FileProgress {
                    file_index: var_fileIndex,
                    total_files: var_totalFiles,
                    current_file: var_currentFile,
                    progress: var_progress,
                };
            }
            1 => {
                let mut var_fileIndex = <u32>::sse_decode(deserializer);
                let mut var_result =
                    <crate::api::crypt_api::FrbDecryptResult>::sse_decode(deserializer);
                return crate::api::crypt_api::FrbBatchDecryptEvent::FileDone {
                    file_index: var_fileIndex,
                    result: var_result,
                };
            }
            2 => {
                let mut var_fileIndex = <u32>::sse_decode(deserializer);
                let mut var_inputPath = <String>::sse_decode(deserializer);
                let mut var_error = <String>::sse_decode(deserializer);
                return crate::api::crypt_api::FrbBatchDecryptEvent::FileError {
                    file_index: var_fileIndex,
                    input_path: var_inputPath,
                    error: var_error,
                };
            }
            3 => {
                let mut var_field0 =
                    <crate::api::crypt_api::FrbBatchDecryptResult>::sse_decode(deserializer);
                return crate::api::crypt_api::FrbBatchDecryptEvent::AllDone(var_field0);
            }
            _ => {
                unimplemented!("");
            }
        }
    }
}

impl SseDecode for crate::api::crypt_api::FrbBatchDecryptOptions {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_inputPaths = <Vec<String>>::sse_decode(deserializer);
        let mut var_outputDir = <String>::sse_decode(deserializer);
        let mut var_password = <String>::sse_decode(deserializer);
        let mut var_tempDir = <Option<String>>::sse_decode(deserializer);
        let mut var_chunkSize =
            <crate::api::crypt_api::FrbChunkSizePreset>::sse_decode(deserializer);
        return crate::api::crypt_api::FrbBatchDecryptOptions {
            input_paths: var_inputPaths,
            output_dir: var_outputDir,
            password: var_password,
            temp_dir: var_tempDir,
            chunk_size: var_chunkSize,
        };
    }
}

impl SseDecode for crate::api::crypt_api::FrbBatchDecryptResult {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_succeeded =
            <Vec<crate::api::crypt_api::FrbDecryptResult>>::sse_decode(deserializer);
        let mut var_failed = <Vec<crate::api::crypt_api::FrbBatchError>>::sse_decode(deserializer);
        return crate::api::crypt_api::FrbBatchDecryptResult {
            succeeded: var_succeeded,
            failed: var_failed,
        };
    }
}

impl SseDecode for crate::api::crypt_api::FrbBatchEncryptEvent {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut tag_ = <i32>::sse_decode(deserializer);
        match tag_ {
            0 => {
                let mut var_fileIndex = <u32>::sse_decode(deserializer);
                let mut var_totalFiles = <u32>::sse_decode(deserializer);
                let mut var_currentFile = <String>::sse_decode(deserializer);
                let mut var_progress =
                    <crate::api::crypt_api::FrbProgressEvent>::sse_decode(deserializer);
                return crate::api::crypt_api::FrbBatchEncryptEvent::FileProgress {
                    file_index: var_fileIndex,
                    total_files: var_totalFiles,
                    current_file: var_currentFile,
                    progress: var_progress,
                };
            }
            1 => {
                let mut var_fileIndex = <u32>::sse_decode(deserializer);
                let mut var_result =
                    <crate::api::crypt_api::FrbEncryptResult>::sse_decode(deserializer);
                return crate::api::crypt_api::FrbBatchEncryptEvent::FileDone {
                    file_index: var_fileIndex,
                    result: var_result,
                };
            }
            2 => {
                let mut var_fileIndex = <u32>::sse_decode(deserializer);
                let mut var_inputPath = <String>::sse_decode(deserializer);
                let mut var_error = <String>::sse_decode(deserializer);
                return crate::api::crypt_api::FrbBatchEncryptEvent::FileError {
                    file_index: var_fileIndex,
                    input_path: var_inputPath,
                    error: var_error,
                };
            }
            3 => {
                let mut var_field0 =
                    <crate::api::crypt_api::FrbBatchEncryptResult>::sse_decode(deserializer);
                return crate::api::crypt_api::FrbBatchEncryptEvent::AllDone(var_field0);
            }
            _ => {
                unimplemented!("");
            }
        }
    }
}

impl SseDecode for crate::api::crypt_api::FrbBatchEncryptOptions {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_inputPaths = <Vec<String>>::sse_decode(deserializer);
        let mut var_outputDir = <String>::sse_decode(deserializer);
        let mut var_password = <String>::sse_decode(deserializer);
        let mut var_gzipCompressed = <bool>::sse_decode(deserializer);
        let mut var_tempDir = <Option<String>>::sse_decode(deserializer);
        let mut var_metadata = <Vec<crate::api::crypt_api::FrbKeyValue>>::sse_decode(deserializer);
        let mut var_chunkSize =
            <crate::api::crypt_api::FrbChunkSizePreset>::sse_decode(deserializer);
        return crate::api::crypt_api::FrbBatchEncryptOptions {
            input_paths: var_inputPaths,
            output_dir: var_outputDir,
            password: var_password,
            gzip_compressed: var_gzipCompressed,
            temp_dir: var_tempDir,
            metadata: var_metadata,
            chunk_size: var_chunkSize,
        };
    }
}

impl SseDecode for crate::api::crypt_api::FrbBatchEncryptResult {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_succeeded =
            <Vec<crate::api::crypt_api::FrbEncryptResult>>::sse_decode(deserializer);
        let mut var_failed = <Vec<crate::api::crypt_api::FrbBatchError>>::sse_decode(deserializer);
        return crate::api::crypt_api::FrbBatchEncryptResult {
            succeeded: var_succeeded,
            failed: var_failed,
        };
    }
}

impl SseDecode for crate::api::crypt_api::FrbBatchError {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_inputPath = <String>::sse_decode(deserializer);
        let mut var_error = <String>::sse_decode(deserializer);
        return crate::api::crypt_api::FrbBatchError {
            input_path: var_inputPath,
            error: var_error,
        };
    }
}

impl SseDecode for crate::api::crypt_api::FrbChunkSizePreset {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut tag_ = <i32>::sse_decode(deserializer);
        match tag_ {
            0 => {
                return crate::api::crypt_api::FrbChunkSizePreset::Desktop;
            }
            1 => {
                return crate::api::crypt_api::FrbChunkSizePreset::Mobile;
            }
            2 => {
                let mut var_field0 = <u32>::sse_decode(deserializer);
                return crate::api::crypt_api::FrbChunkSizePreset::Custom(var_field0);
            }
            _ => {
                unimplemented!("");
            }
        }
    }
}

impl SseDecode for crate::api::crypt_api::FrbDecryptEvent {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut tag_ = <i32>::sse_decode(deserializer);
        match tag_ {
            0 => {
                let mut var_field0 =
                    <crate::api::crypt_api::FrbProgressEvent>::sse_decode(deserializer);
                return crate::api::crypt_api::FrbDecryptEvent::Progress(var_field0);
            }
            1 => {
                let mut var_field0 =
                    <crate::api::crypt_api::FrbDecryptResult>::sse_decode(deserializer);
                return crate::api::crypt_api::FrbDecryptEvent::Done(var_field0);
            }
            2 => {
                let mut var_field0 = <String>::sse_decode(deserializer);
                return crate::api::crypt_api::FrbDecryptEvent::Error(var_field0);
            }
            _ => {
                unimplemented!("");
            }
        }
    }
}

impl SseDecode for crate::api::crypt_api::FrbDecryptOptions {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_inputPath = <String>::sse_decode(deserializer);
        let mut var_outputDir = <String>::sse_decode(deserializer);
        let mut var_password = <String>::sse_decode(deserializer);
        let mut var_tempDir = <Option<String>>::sse_decode(deserializer);
        let mut var_chunkSize =
            <crate::api::crypt_api::FrbChunkSizePreset>::sse_decode(deserializer);
        return crate::api::crypt_api::FrbDecryptOptions {
            input_path: var_inputPath,
            output_dir: var_outputDir,
            password: var_password,
            temp_dir: var_tempDir,
            chunk_size: var_chunkSize,
        };
    }
}

impl SseDecode for crate::api::crypt_api::FrbDecryptResult {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_outputPath = <String>::sse_decode(deserializer);
        let mut var_metadata =
            <crate::api::crypt_api::FrbDecryptedMetadata>::sse_decode(deserializer);
        return crate::api::crypt_api::FrbDecryptResult {
            output_path: var_outputPath,
            metadata: var_metadata,
        };
    }
}

impl SseDecode for crate::api::crypt_api::FrbDecryptedMetadata {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_originalFilename = <String>::sse_decode(deserializer);
        let mut var_originalExtension = <String>::sse_decode(deserializer);
        let mut var_gzipCompressed = <bool>::sse_decode(deserializer);
        let mut var_originalSize = <u64>::sse_decode(deserializer);
        let mut var_uuid = <String>::sse_decode(deserializer);
        let mut var_metadata = <Vec<crate::api::crypt_api::FrbKeyValue>>::sse_decode(deserializer);
        return crate::api::crypt_api::FrbDecryptedMetadata {
            original_filename: var_originalFilename,
            original_extension: var_originalExtension,
            gzip_compressed: var_gzipCompressed,
            original_size: var_originalSize,
            uuid: var_uuid,
            metadata: var_metadata,
        };
    }
}

impl SseDecode for crate::api::crypt_api::FrbEncryptEvent {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut tag_ = <i32>::sse_decode(deserializer);
        match tag_ {
            0 => {
                let mut var_field0 =
                    <crate::api::crypt_api::FrbProgressEvent>::sse_decode(deserializer);
                return crate::api::crypt_api::FrbEncryptEvent::Progress(var_field0);
            }
            1 => {
                let mut var_field0 =
                    <crate::api::crypt_api::FrbEncryptResult>::sse_decode(deserializer);
                return crate::api::crypt_api::FrbEncryptEvent::Done(var_field0);
            }
            2 => {
                let mut var_field0 = <String>::sse_decode(deserializer);
                return crate::api::crypt_api::FrbEncryptEvent::Error(var_field0);
            }
            _ => {
                unimplemented!("");
            }
        }
    }
}

impl SseDecode for crate::api::crypt_api::FrbEncryptOptions {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_inputPath = <String>::sse_decode(deserializer);
        let mut var_outputDir = <String>::sse_decode(deserializer);
        let mut var_password = <String>::sse_decode(deserializer);
        let mut var_gzipCompressed = <bool>::sse_decode(deserializer);
        let mut var_uuid = <Option<String>>::sse_decode(deserializer);
        let mut var_outputExtension = <Option<String>>::sse_decode(deserializer);
        let mut var_tempDir = <Option<String>>::sse_decode(deserializer);
        let mut var_metadata = <Vec<crate::api::crypt_api::FrbKeyValue>>::sse_decode(deserializer);
        let mut var_chunkSize =
            <crate::api::crypt_api::FrbChunkSizePreset>::sse_decode(deserializer);
        return crate::api::crypt_api::FrbEncryptOptions {
            input_path: var_inputPath,
            output_dir: var_outputDir,
            password: var_password,
            gzip_compressed: var_gzipCompressed,
            uuid: var_uuid,
            output_extension: var_outputExtension,
            temp_dir: var_tempDir,
            metadata: var_metadata,
            chunk_size: var_chunkSize,
        };
    }
}

impl SseDecode for crate::api::crypt_api::FrbEncryptResult {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_outputPath = <String>::sse_decode(deserializer);
        let mut var_uuid = <String>::sse_decode(deserializer);
        let mut var_originalSize = <u64>::sse_decode(deserializer);
        return crate::api::crypt_api::FrbEncryptResult {
            output_path: var_outputPath,
            uuid: var_uuid,
            original_size: var_originalSize,
        };
    }
}

impl SseDecode for crate::api::crypt_api::FrbKeyValue {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_key = <String>::sse_decode(deserializer);
        let mut var_value = <String>::sse_decode(deserializer);
        return crate::api::crypt_api::FrbKeyValue {
            key: var_key,
            value: var_value,
        };
    }
}

impl SseDecode for crate::api::crypt_api::FrbProgressEvent {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_stage = <crate::api::crypt_api::FrbProgressStage>::sse_decode(deserializer);
        let mut var_bytesProcessed = <u64>::sse_decode(deserializer);
        let mut var_totalBytes = <u64>::sse_decode(deserializer);
        let mut var_percentage = <f64>::sse_decode(deserializer);
        return crate::api::crypt_api::FrbProgressEvent {
            stage: var_stage,
            bytes_processed: var_bytesProcessed,
            total_bytes: var_totalBytes,
            percentage: var_percentage,
        };
    }
}

impl SseDecode for crate::api::crypt_api::FrbProgressStage {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <i32>::sse_decode(deserializer);
        return match inner {
            0 => crate::api::crypt_api::FrbProgressStage::CompressingDirectory,
            1 => crate::api::crypt_api::FrbProgressStage::CompressingGzip,
            2 => crate::api::crypt_api::FrbProgressStage::Encrypting,
            3 => crate::api::crypt_api::FrbProgressStage::Decrypting,
            4 => crate::api::crypt_api::FrbProgressStage::DecompressingGzip,
            5 => crate::api::crypt_api::FrbProgressStage::DecompressingDirectory,
            6 => crate::api::crypt_api::FrbProgressStage::Done,
            _ => unreachable!("Invalid variant for FrbProgressStage: {}", inner),
        };
    }
}

impl SseDecode for i32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_i32::<NativeEndian>().unwrap()
    }
}

impl SseDecode for i64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_i64::<NativeEndian>().unwrap()
    }
}

impl SseDecode for Vec<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = vec![];
        for idx_ in 0..len_ {
            ans_.push(<String>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::api::crypt_api::FrbBatchError> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = vec![];
        for idx_ in 0..len_ {
            ans_.push(<crate::api::crypt_api::FrbBatchError>::sse_decode(
                deserializer,
            ));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::api::crypt_api::FrbDecryptResult> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = vec![];
        for idx_ in 0..len_ {
            ans_.push(<crate::api::crypt_api::FrbDecryptResult>::sse_decode(
                deserializer,
            ));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::api::crypt_api::FrbEncryptResult> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = vec![];
        for idx_ in 0..len_ {
            ans_.push(<crate::api::crypt_api::FrbEncryptResult>::sse_decode(
                deserializer,
            ));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::api::crypt_api::FrbKeyValue> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = vec![];
        for idx_ in 0..len_ {
            ans_.push(<crate::api::crypt_api::FrbKeyValue>::sse_decode(
                deserializer,
            ));
        }
        return ans_;
    }
}

impl SseDecode for Vec<u8> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = vec![];
        for idx_ in 0..len_ {
            ans_.push(<u8>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for crate::api::logging::LogEntry {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_timeMillis = <i64>::sse_decode(deserializer);
        let mut var_level = <i32>::sse_decode(deserializer);
        let mut var_tag = <String>::sse_decode(deserializer);
        let mut var_msg = <String>::sse_decode(deserializer);
        return crate::api::logging::LogEntry {
            time_millis: var_timeMillis,
            level: var_level,
            tag: var_tag,
            msg: var_msg,
        };
    }
}

impl SseDecode for Option<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<String>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for u32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u32::<NativeEndian>().unwrap()
    }
}

impl SseDecode for u64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u64::<NativeEndian>().unwrap()
    }
}

impl SseDecode for u8 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u8().unwrap()
    }
}

impl SseDecode for () {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {}
}

fn pde_ffi_dispatcher_primary_impl(
    func_id: i32,
    port: flutter_rust_bridge::for_generated::MessagePort,
    ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len: i32,
    data_len: i32,
) {
    // Codec=Pde (Serialization + dispatch), see doc to use other codecs
    match func_id {
        1 => wire__crate__api__logging__create_log_stream_impl(port, ptr, rust_vec_len, data_len),
        2 => wire__crate__api__crypt_api__decrypt_batch_impl(port, ptr, rust_vec_len, data_len),
        3 => wire__crate__api__crypt_api__decrypt_file_impl(port, ptr, rust_vec_len, data_len),
        4 => wire__crate__api__crypt_api__encrypt_batch_impl(port, ptr, rust_vec_len, data_len),
        5 => wire__crate__api__crypt_api__encrypt_file_impl(port, ptr, rust_vec_len, data_len),
        6 => wire__crate__api__crypt_api__frb_decrypt_options_simple_impl(
            port,
            ptr,
            rust_vec_len,
            data_len,
        ),
        7 => wire__crate__api__crypt_api__frb_encrypt_options_simple_impl(
            port,
            ptr,
            rust_vec_len,
            data_len,
        ),
        9 => wire__crate__api__simple__init_app_impl(port, ptr, rust_vec_len, data_len),
        10 => wire__crate__api__logging__install_rust_log_bridge_impl(
            port,
            ptr,
            rust_vec_len,
            data_len,
        ),
        11 => wire__crate__api__crypt_api__read_encrypted_header_impl(
            port,
            ptr,
            rust_vec_len,
            data_len,
        ),
        12 => wire__crate__api__logging__rust_log_impl(port, ptr, rust_vec_len, data_len),
        13 => wire__crate__api__logging__rust_log_debug_impl(port, ptr, rust_vec_len, data_len),
        14 => wire__crate__api__logging__rust_log_error_impl(port, ptr, rust_vec_len, data_len),
        15 => wire__crate__api__logging__rust_log_fatal_impl(port, ptr, rust_vec_len, data_len),
        16 => wire__crate__api__logging__rust_log_info_impl(port, ptr, rust_vec_len, data_len),
        17 => wire__crate__api__logging__rust_log_warning_impl(port, ptr, rust_vec_len, data_len),
        _ => unreachable!(),
    }
}

fn pde_ffi_dispatcher_sync_impl(
    func_id: i32,
    ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len: i32,
    data_len: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    // Codec=Pde (Serialization + dispatch), see doc to use other codecs
    match func_id {
        8 => wire__crate__api__simple__greet_impl(ptr, rust_vec_len, data_len),
        _ => unreachable!(),
    }
}

// Section: rust2dart

// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::crypt_api::FrbBatchDecryptEvent {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            crate::api::crypt_api::FrbBatchDecryptEvent::FileProgress {
                file_index,
                total_files,
                current_file,
                progress,
            } => [
                0.into_dart(),
                file_index.into_into_dart().into_dart(),
                total_files.into_into_dart().into_dart(),
                current_file.into_into_dart().into_dart(),
                progress.into_into_dart().into_dart(),
            ]
            .into_dart(),
            crate::api::crypt_api::FrbBatchDecryptEvent::FileDone { file_index, result } => [
                1.into_dart(),
                file_index.into_into_dart().into_dart(),
                result.into_into_dart().into_dart(),
            ]
            .into_dart(),
            crate::api::crypt_api::FrbBatchDecryptEvent::FileError {
                file_index,
                input_path,
                error,
            } => [
                2.into_dart(),
                file_index.into_into_dart().into_dart(),
                input_path.into_into_dart().into_dart(),
                error.into_into_dart().into_dart(),
            ]
            .into_dart(),
            crate::api::crypt_api::FrbBatchDecryptEvent::AllDone(field0) => {
                [3.into_dart(), field0.into_into_dart().into_dart()].into_dart()
            }
            _ => {
                unimplemented!("");
            }
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::crypt_api::FrbBatchDecryptEvent
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::crypt_api::FrbBatchDecryptEvent>
    for crate::api::crypt_api::FrbBatchDecryptEvent
{
    fn into_into_dart(self) -> crate::api::crypt_api::FrbBatchDecryptEvent {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::crypt_api::FrbBatchDecryptOptions {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.input_paths.into_into_dart().into_dart(),
            self.output_dir.into_into_dart().into_dart(),
            self.password.into_into_dart().into_dart(),
            self.temp_dir.into_into_dart().into_dart(),
            self.chunk_size.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::crypt_api::FrbBatchDecryptOptions
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::crypt_api::FrbBatchDecryptOptions>
    for crate::api::crypt_api::FrbBatchDecryptOptions
{
    fn into_into_dart(self) -> crate::api::crypt_api::FrbBatchDecryptOptions {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::crypt_api::FrbBatchDecryptResult {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.succeeded.into_into_dart().into_dart(),
            self.failed.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::crypt_api::FrbBatchDecryptResult
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::crypt_api::FrbBatchDecryptResult>
    for crate::api::crypt_api::FrbBatchDecryptResult
{
    fn into_into_dart(self) -> crate::api::crypt_api::FrbBatchDecryptResult {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::crypt_api::FrbBatchEncryptEvent {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            crate::api::crypt_api::FrbBatchEncryptEvent::FileProgress {
                file_index,
                total_files,
                current_file,
                progress,
            } => [
                0.into_dart(),
                file_index.into_into_dart().into_dart(),
                total_files.into_into_dart().into_dart(),
                current_file.into_into_dart().into_dart(),
                progress.into_into_dart().into_dart(),
            ]
            .into_dart(),
            crate::api::crypt_api::FrbBatchEncryptEvent::FileDone { file_index, result } => [
                1.into_dart(),
                file_index.into_into_dart().into_dart(),
                result.into_into_dart().into_dart(),
            ]
            .into_dart(),
            crate::api::crypt_api::FrbBatchEncryptEvent::FileError {
                file_index,
                input_path,
                error,
            } => [
                2.into_dart(),
                file_index.into_into_dart().into_dart(),
                input_path.into_into_dart().into_dart(),
                error.into_into_dart().into_dart(),
            ]
            .into_dart(),
            crate::api::crypt_api::FrbBatchEncryptEvent::AllDone(field0) => {
                [3.into_dart(), field0.into_into_dart().into_dart()].into_dart()
            }
            _ => {
                unimplemented!("");
            }
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::crypt_api::FrbBatchEncryptEvent
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::crypt_api::FrbBatchEncryptEvent>
    for crate::api::crypt_api::FrbBatchEncryptEvent
{
    fn into_into_dart(self) -> crate::api::crypt_api::FrbBatchEncryptEvent {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::crypt_api::FrbBatchEncryptOptions {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.input_paths.into_into_dart().into_dart(),
            self.output_dir.into_into_dart().into_dart(),
            self.password.into_into_dart().into_dart(),
            self.gzip_compressed.into_into_dart().into_dart(),
            self.temp_dir.into_into_dart().into_dart(),
            self.metadata.into_into_dart().into_dart(),
            self.chunk_size.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::crypt_api::FrbBatchEncryptOptions
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::crypt_api::FrbBatchEncryptOptions>
    for crate::api::crypt_api::FrbBatchEncryptOptions
{
    fn into_into_dart(self) -> crate::api::crypt_api::FrbBatchEncryptOptions {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::crypt_api::FrbBatchEncryptResult {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.succeeded.into_into_dart().into_dart(),
            self.failed.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::crypt_api::FrbBatchEncryptResult
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::crypt_api::FrbBatchEncryptResult>
    for crate::api::crypt_api::FrbBatchEncryptResult
{
    fn into_into_dart(self) -> crate::api::crypt_api::FrbBatchEncryptResult {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::crypt_api::FrbBatchError {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.input_path.into_into_dart().into_dart(),
            self.error.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::crypt_api::FrbBatchError
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::crypt_api::FrbBatchError>
    for crate::api::crypt_api::FrbBatchError
{
    fn into_into_dart(self) -> crate::api::crypt_api::FrbBatchError {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::crypt_api::FrbChunkSizePreset {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            crate::api::crypt_api::FrbChunkSizePreset::Desktop => [0.into_dart()].into_dart(),
            crate::api::crypt_api::FrbChunkSizePreset::Mobile => [1.into_dart()].into_dart(),
            crate::api::crypt_api::FrbChunkSizePreset::Custom(field0) => {
                [2.into_dart(), field0.into_into_dart().into_dart()].into_dart()
            }
            _ => {
                unimplemented!("");
            }
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::crypt_api::FrbChunkSizePreset
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::crypt_api::FrbChunkSizePreset>
    for crate::api::crypt_api::FrbChunkSizePreset
{
    fn into_into_dart(self) -> crate::api::crypt_api::FrbChunkSizePreset {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::crypt_api::FrbDecryptEvent {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            crate::api::crypt_api::FrbDecryptEvent::Progress(field0) => {
                [0.into_dart(), field0.into_into_dart().into_dart()].into_dart()
            }
            crate::api::crypt_api::FrbDecryptEvent::Done(field0) => {
                [1.into_dart(), field0.into_into_dart().into_dart()].into_dart()
            }
            crate::api::crypt_api::FrbDecryptEvent::Error(field0) => {
                [2.into_dart(), field0.into_into_dart().into_dart()].into_dart()
            }
            _ => {
                unimplemented!("");
            }
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::crypt_api::FrbDecryptEvent
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::crypt_api::FrbDecryptEvent>
    for crate::api::crypt_api::FrbDecryptEvent
{
    fn into_into_dart(self) -> crate::api::crypt_api::FrbDecryptEvent {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::crypt_api::FrbDecryptOptions {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.input_path.into_into_dart().into_dart(),
            self.output_dir.into_into_dart().into_dart(),
            self.password.into_into_dart().into_dart(),
            self.temp_dir.into_into_dart().into_dart(),
            self.chunk_size.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::crypt_api::FrbDecryptOptions
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::crypt_api::FrbDecryptOptions>
    for crate::api::crypt_api::FrbDecryptOptions
{
    fn into_into_dart(self) -> crate::api::crypt_api::FrbDecryptOptions {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::crypt_api::FrbDecryptResult {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.output_path.into_into_dart().into_dart(),
            self.metadata.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::crypt_api::FrbDecryptResult
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::crypt_api::FrbDecryptResult>
    for crate::api::crypt_api::FrbDecryptResult
{
    fn into_into_dart(self) -> crate::api::crypt_api::FrbDecryptResult {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::crypt_api::FrbDecryptedMetadata {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.original_filename.into_into_dart().into_dart(),
            self.original_extension.into_into_dart().into_dart(),
            self.gzip_compressed.into_into_dart().into_dart(),
            self.original_size.into_into_dart().into_dart(),
            self.uuid.into_into_dart().into_dart(),
            self.metadata.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::crypt_api::FrbDecryptedMetadata
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::crypt_api::FrbDecryptedMetadata>
    for crate::api::crypt_api::FrbDecryptedMetadata
{
    fn into_into_dart(self) -> crate::api::crypt_api::FrbDecryptedMetadata {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::crypt_api::FrbEncryptEvent {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            crate::api::crypt_api::FrbEncryptEvent::Progress(field0) => {
                [0.into_dart(), field0.into_into_dart().into_dart()].into_dart()
            }
            crate::api::crypt_api::FrbEncryptEvent::Done(field0) => {
                [1.into_dart(), field0.into_into_dart().into_dart()].into_dart()
            }
            crate::api::crypt_api::FrbEncryptEvent::Error(field0) => {
                [2.into_dart(), field0.into_into_dart().into_dart()].into_dart()
            }
            _ => {
                unimplemented!("");
            }
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::crypt_api::FrbEncryptEvent
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::crypt_api::FrbEncryptEvent>
    for crate::api::crypt_api::FrbEncryptEvent
{
    fn into_into_dart(self) -> crate::api::crypt_api::FrbEncryptEvent {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::crypt_api::FrbEncryptOptions {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.input_path.into_into_dart().into_dart(),
            self.output_dir.into_into_dart().into_dart(),
            self.password.into_into_dart().into_dart(),
            self.gzip_compressed.into_into_dart().into_dart(),
            self.uuid.into_into_dart().into_dart(),
            self.output_extension.into_into_dart().into_dart(),
            self.temp_dir.into_into_dart().into_dart(),
            self.metadata.into_into_dart().into_dart(),
            self.chunk_size.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::crypt_api::FrbEncryptOptions
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::crypt_api::FrbEncryptOptions>
    for crate::api::crypt_api::FrbEncryptOptions
{
    fn into_into_dart(self) -> crate::api::crypt_api::FrbEncryptOptions {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::crypt_api::FrbEncryptResult {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.output_path.into_into_dart().into_dart(),
            self.uuid.into_into_dart().into_dart(),
            self.original_size.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::crypt_api::FrbEncryptResult
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::crypt_api::FrbEncryptResult>
    for crate::api::crypt_api::FrbEncryptResult
{
    fn into_into_dart(self) -> crate::api::crypt_api::FrbEncryptResult {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::crypt_api::FrbKeyValue {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.key.into_into_dart().into_dart(),
            self.value.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::crypt_api::FrbKeyValue
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::crypt_api::FrbKeyValue>
    for crate::api::crypt_api::FrbKeyValue
{
    fn into_into_dart(self) -> crate::api::crypt_api::FrbKeyValue {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::crypt_api::FrbProgressEvent {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.stage.into_into_dart().into_dart(),
            self.bytes_processed.into_into_dart().into_dart(),
            self.total_bytes.into_into_dart().into_dart(),
            self.percentage.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::crypt_api::FrbProgressEvent
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::crypt_api::FrbProgressEvent>
    for crate::api::crypt_api::FrbProgressEvent
{
    fn into_into_dart(self) -> crate::api::crypt_api::FrbProgressEvent {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::crypt_api::FrbProgressStage {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            Self::CompressingDirectory => 0.into_dart(),
            Self::CompressingGzip => 1.into_dart(),
            Self::Encrypting => 2.into_dart(),
            Self::Decrypting => 3.into_dart(),
            Self::DecompressingGzip => 4.into_dart(),
            Self::DecompressingDirectory => 5.into_dart(),
            Self::Done => 6.into_dart(),
            _ => unreachable!(),
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::crypt_api::FrbProgressStage
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::crypt_api::FrbProgressStage>
    for crate::api::crypt_api::FrbProgressStage
{
    fn into_into_dart(self) -> crate::api::crypt_api::FrbProgressStage {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::logging::LogEntry {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.time_millis.into_into_dart().into_dart(),
            self.level.into_into_dart().into_dart(),
            self.tag.into_into_dart().into_dart(),
            self.msg.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::logging::LogEntry {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::logging::LogEntry>
    for crate::api::logging::LogEntry
{
    fn into_into_dart(self) -> crate::api::logging::LogEntry {
        self
    }
}

impl SseEncode for flutter_rust_bridge::for_generated::anyhow::Error {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(format!("{:?}", self), serializer);
    }
}

impl SseEncode
    for StreamSink<
        crate::api::crypt_api::FrbBatchDecryptEvent,
        flutter_rust_bridge::for_generated::SseCodec,
    >
{
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        unimplemented!("")
    }
}

impl SseEncode
    for StreamSink<
        crate::api::crypt_api::FrbBatchEncryptEvent,
        flutter_rust_bridge::for_generated::SseCodec,
    >
{
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        unimplemented!("")
    }
}

impl SseEncode
    for StreamSink<
        crate::api::crypt_api::FrbDecryptEvent,
        flutter_rust_bridge::for_generated::SseCodec,
    >
{
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        unimplemented!("")
    }
}

impl SseEncode
    for StreamSink<
        crate::api::crypt_api::FrbEncryptEvent,
        flutter_rust_bridge::for_generated::SseCodec,
    >
{
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        unimplemented!("")
    }
}

impl SseEncode
    for StreamSink<crate::api::logging::LogEntry, flutter_rust_bridge::for_generated::SseCodec>
{
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        unimplemented!("")
    }
}

impl SseEncode for String {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Vec<u8>>::sse_encode(self.into_bytes(), serializer);
    }
}

impl SseEncode for bool {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u8(self as _).unwrap();
    }
}

impl SseEncode for f64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_f64::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for crate::api::crypt_api::FrbBatchDecryptEvent {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        match self {
            crate::api::crypt_api::FrbBatchDecryptEvent::FileProgress {
                file_index,
                total_files,
                current_file,
                progress,
            } => {
                <i32>::sse_encode(0, serializer);
                <u32>::sse_encode(file_index, serializer);
                <u32>::sse_encode(total_files, serializer);
                <String>::sse_encode(current_file, serializer);
                <crate::api::crypt_api::FrbProgressEvent>::sse_encode(progress, serializer);
            }
            crate::api::crypt_api::FrbBatchDecryptEvent::FileDone { file_index, result } => {
                <i32>::sse_encode(1, serializer);
                <u32>::sse_encode(file_index, serializer);
                <crate::api::crypt_api::FrbDecryptResult>::sse_encode(result, serializer);
            }
            crate::api::crypt_api::FrbBatchDecryptEvent::FileError {
                file_index,
                input_path,
                error,
            } => {
                <i32>::sse_encode(2, serializer);
                <u32>::sse_encode(file_index, serializer);
                <String>::sse_encode(input_path, serializer);
                <String>::sse_encode(error, serializer);
            }
            crate::api::crypt_api::FrbBatchDecryptEvent::AllDone(field0) => {
                <i32>::sse_encode(3, serializer);
                <crate::api::crypt_api::FrbBatchDecryptResult>::sse_encode(field0, serializer);
            }
            _ => {
                unimplemented!("");
            }
        }
    }
}

impl SseEncode for crate::api::crypt_api::FrbBatchDecryptOptions {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Vec<String>>::sse_encode(self.input_paths, serializer);
        <String>::sse_encode(self.output_dir, serializer);
        <String>::sse_encode(self.password, serializer);
        <Option<String>>::sse_encode(self.temp_dir, serializer);
        <crate::api::crypt_api::FrbChunkSizePreset>::sse_encode(self.chunk_size, serializer);
    }
}

impl SseEncode for crate::api::crypt_api::FrbBatchDecryptResult {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Vec<crate::api::crypt_api::FrbDecryptResult>>::sse_encode(self.succeeded, serializer);
        <Vec<crate::api::crypt_api::FrbBatchError>>::sse_encode(self.failed, serializer);
    }
}

impl SseEncode for crate::api::crypt_api::FrbBatchEncryptEvent {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        match self {
            crate::api::crypt_api::FrbBatchEncryptEvent::FileProgress {
                file_index,
                total_files,
                current_file,
                progress,
            } => {
                <i32>::sse_encode(0, serializer);
                <u32>::sse_encode(file_index, serializer);
                <u32>::sse_encode(total_files, serializer);
                <String>::sse_encode(current_file, serializer);
                <crate::api::crypt_api::FrbProgressEvent>::sse_encode(progress, serializer);
            }
            crate::api::crypt_api::FrbBatchEncryptEvent::FileDone { file_index, result } => {
                <i32>::sse_encode(1, serializer);
                <u32>::sse_encode(file_index, serializer);
                <crate::api::crypt_api::FrbEncryptResult>::sse_encode(result, serializer);
            }
            crate::api::crypt_api::FrbBatchEncryptEvent::FileError {
                file_index,
                input_path,
                error,
            } => {
                <i32>::sse_encode(2, serializer);
                <u32>::sse_encode(file_index, serializer);
                <String>::sse_encode(input_path, serializer);
                <String>::sse_encode(error, serializer);
            }
            crate::api::crypt_api::FrbBatchEncryptEvent::AllDone(field0) => {
                <i32>::sse_encode(3, serializer);
                <crate::api::crypt_api::FrbBatchEncryptResult>::sse_encode(field0, serializer);
            }
            _ => {
                unimplemented!("");
            }
        }
    }
}

impl SseEncode for crate::api::crypt_api::FrbBatchEncryptOptions {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Vec<String>>::sse_encode(self.input_paths, serializer);
        <String>::sse_encode(self.output_dir, serializer);
        <String>::sse_encode(self.password, serializer);
        <bool>::sse_encode(self.gzip_compressed, serializer);
        <Option<String>>::sse_encode(self.temp_dir, serializer);
        <Vec<crate::api::crypt_api::FrbKeyValue>>::sse_encode(self.metadata, serializer);
        <crate::api::crypt_api::FrbChunkSizePreset>::sse_encode(self.chunk_size, serializer);
    }
}

impl SseEncode for crate::api::crypt_api::FrbBatchEncryptResult {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Vec<crate::api::crypt_api::FrbEncryptResult>>::sse_encode(self.succeeded, serializer);
        <Vec<crate::api::crypt_api::FrbBatchError>>::sse_encode(self.failed, serializer);
    }
}

impl SseEncode for crate::api::crypt_api::FrbBatchError {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.input_path, serializer);
        <String>::sse_encode(self.error, serializer);
    }
}

impl SseEncode for crate::api::crypt_api::FrbChunkSizePreset {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        match self {
            crate::api::crypt_api::FrbChunkSizePreset::Desktop => {
                <i32>::sse_encode(0, serializer);
            }
            crate::api::crypt_api::FrbChunkSizePreset::Mobile => {
                <i32>::sse_encode(1, serializer);
            }
            crate::api::crypt_api::FrbChunkSizePreset::Custom(field0) => {
                <i32>::sse_encode(2, serializer);
                <u32>::sse_encode(field0, serializer);
            }
            _ => {
                unimplemented!("");
            }
        }
    }
}

impl SseEncode for crate::api::crypt_api::FrbDecryptEvent {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        match self {
            crate::api::crypt_api::FrbDecryptEvent::Progress(field0) => {
                <i32>::sse_encode(0, serializer);
                <crate::api::crypt_api::FrbProgressEvent>::sse_encode(field0, serializer);
            }
            crate::api::crypt_api::FrbDecryptEvent::Done(field0) => {
                <i32>::sse_encode(1, serializer);
                <crate::api::crypt_api::FrbDecryptResult>::sse_encode(field0, serializer);
            }
            crate::api::crypt_api::FrbDecryptEvent::Error(field0) => {
                <i32>::sse_encode(2, serializer);
                <String>::sse_encode(field0, serializer);
            }
            _ => {
                unimplemented!("");
            }
        }
    }
}

impl SseEncode for crate::api::crypt_api::FrbDecryptOptions {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.input_path, serializer);
        <String>::sse_encode(self.output_dir, serializer);
        <String>::sse_encode(self.password, serializer);
        <Option<String>>::sse_encode(self.temp_dir, serializer);
        <crate::api::crypt_api::FrbChunkSizePreset>::sse_encode(self.chunk_size, serializer);
    }
}

impl SseEncode for crate::api::crypt_api::FrbDecryptResult {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.output_path, serializer);
        <crate::api::crypt_api::FrbDecryptedMetadata>::sse_encode(self.metadata, serializer);
    }
}

impl SseEncode for crate::api::crypt_api::FrbDecryptedMetadata {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.original_filename, serializer);
        <String>::sse_encode(self.original_extension, serializer);
        <bool>::sse_encode(self.gzip_compressed, serializer);
        <u64>::sse_encode(self.original_size, serializer);
        <String>::sse_encode(self.uuid, serializer);
        <Vec<crate::api::crypt_api::FrbKeyValue>>::sse_encode(self.metadata, serializer);
    }
}

impl SseEncode for crate::api::crypt_api::FrbEncryptEvent {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        match self {
            crate::api::crypt_api::FrbEncryptEvent::Progress(field0) => {
                <i32>::sse_encode(0, serializer);
                <crate::api::crypt_api::FrbProgressEvent>::sse_encode(field0, serializer);
            }
            crate::api::crypt_api::FrbEncryptEvent::Done(field0) => {
                <i32>::sse_encode(1, serializer);
                <crate::api::crypt_api::FrbEncryptResult>::sse_encode(field0, serializer);
            }
            crate::api::crypt_api::FrbEncryptEvent::Error(field0) => {
                <i32>::sse_encode(2, serializer);
                <String>::sse_encode(field0, serializer);
            }
            _ => {
                unimplemented!("");
            }
        }
    }
}

impl SseEncode for crate::api::crypt_api::FrbEncryptOptions {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.input_path, serializer);
        <String>::sse_encode(self.output_dir, serializer);
        <String>::sse_encode(self.password, serializer);
        <bool>::sse_encode(self.gzip_compressed, serializer);
        <Option<String>>::sse_encode(self.uuid, serializer);
        <Option<String>>::sse_encode(self.output_extension, serializer);
        <Option<String>>::sse_encode(self.temp_dir, serializer);
        <Vec<crate::api::crypt_api::FrbKeyValue>>::sse_encode(self.metadata, serializer);
        <crate::api::crypt_api::FrbChunkSizePreset>::sse_encode(self.chunk_size, serializer);
    }
}

impl SseEncode for crate::api::crypt_api::FrbEncryptResult {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.output_path, serializer);
        <String>::sse_encode(self.uuid, serializer);
        <u64>::sse_encode(self.original_size, serializer);
    }
}

impl SseEncode for crate::api::crypt_api::FrbKeyValue {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.key, serializer);
        <String>::sse_encode(self.value, serializer);
    }
}

impl SseEncode for crate::api::crypt_api::FrbProgressEvent {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <crate::api::crypt_api::FrbProgressStage>::sse_encode(self.stage, serializer);
        <u64>::sse_encode(self.bytes_processed, serializer);
        <u64>::sse_encode(self.total_bytes, serializer);
        <f64>::sse_encode(self.percentage, serializer);
    }
}

impl SseEncode for crate::api::crypt_api::FrbProgressStage {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(
            match self {
                crate::api::crypt_api::FrbProgressStage::CompressingDirectory => 0,
                crate::api::crypt_api::FrbProgressStage::CompressingGzip => 1,
                crate::api::crypt_api::FrbProgressStage::Encrypting => 2,
                crate::api::crypt_api::FrbProgressStage::Decrypting => 3,
                crate::api::crypt_api::FrbProgressStage::DecompressingGzip => 4,
                crate::api::crypt_api::FrbProgressStage::DecompressingDirectory => 5,
                crate::api::crypt_api::FrbProgressStage::Done => 6,
                _ => {
                    unimplemented!("");
                }
            },
            serializer,
        );
    }
}

impl SseEncode for i32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_i32::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for i64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_i64::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for Vec<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <String>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::api::crypt_api::FrbBatchError> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::api::crypt_api::FrbBatchError>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::api::crypt_api::FrbDecryptResult> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::api::crypt_api::FrbDecryptResult>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::api::crypt_api::FrbEncryptResult> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::api::crypt_api::FrbEncryptResult>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::api::crypt_api::FrbKeyValue> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::api::crypt_api::FrbKeyValue>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<u8> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <u8>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for crate::api::logging::LogEntry {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i64>::sse_encode(self.time_millis, serializer);
        <i32>::sse_encode(self.level, serializer);
        <String>::sse_encode(self.tag, serializer);
        <String>::sse_encode(self.msg, serializer);
    }
}

impl SseEncode for Option<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <String>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for u32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u32::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for u64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u64::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for u8 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u8(self).unwrap();
    }
}

impl SseEncode for () {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {}
}

#[cfg(not(target_family = "wasm"))]
mod io {
    // This file is automatically generated, so please do not edit it.
    // @generated by `flutter_rust_bridge`@ 2.11.1.

    // Section: imports

    use super::*;
    use flutter_rust_bridge::for_generated::byteorder::{
        NativeEndian, ReadBytesExt, WriteBytesExt,
    };
    use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
    use flutter_rust_bridge::{Handler, IntoIntoDart};

    // Section: boilerplate

    flutter_rust_bridge::frb_generated_boilerplate_io!();
}
#[cfg(not(target_family = "wasm"))]
pub use io::*;

/// cbindgen:ignore
#[cfg(target_family = "wasm")]
mod web {
    // This file is automatically generated, so please do not edit it.
    // @generated by `flutter_rust_bridge`@ 2.11.1.

    // Section: imports

    use super::*;
    use flutter_rust_bridge::for_generated::byteorder::{
        NativeEndian, ReadBytesExt, WriteBytesExt,
    };
    use flutter_rust_bridge::for_generated::wasm_bindgen;
    use flutter_rust_bridge::for_generated::wasm_bindgen::prelude::*;
    use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
    use flutter_rust_bridge::{Handler, IntoIntoDart};

    // Section: boilerplate

    flutter_rust_bridge::frb_generated_boilerplate_web!();
}
#[cfg(target_family = "wasm")]
pub use web::*;
