import 'tables.dart';

/// Агрегированный список всех индексов базы данных.
final List<String> allTableIndexes = [
  ...apiKeyHistoryTableIndexes,
  ...apiKeyItemsTableIndexes,
  ...bankCardHistoryTableIndexes,
  ...bankCardItemsTableIndexes,
  ...certificateHistoryTableIndexes,
  ...certificateItemsTableIndexes,
  ...contactHistoryTableIndexes,
  ...contactItemsTableIndexes,
  ...cryptoWalletHistoryTableIndexes,
  ...cryptoWalletItemsTableIndexes,
  ...documentItemsTableIndexes,
  ...documentPagesTableIndexes,
  ...documentVersionPagesTableIndexes,
  ...documentVersionsTableIndexes,
  ...fileHistoryTableIndexes,
  ...fileItemsTableIndexes,
  ...fileMetadataTableIndexes,
  ...fileMetadataHistoryTableIndexes,
  ...identityHistoryTableIndexes,
  ...identityItemsTableIndexes,
  ...licenseKeyHistoryTableIndexes,
  ...licenseKeyItemsTableIndexes,
  ...loyaltyCardHistoryTableIndexes,
  ...loyaltyCardItemsTableIndexes,
  ...otpHistoryTableIndexes,
  ...otpItemsTableIndexes,
  ...passwordHistoryTableIndexes,
  ...passwordItemsTableIndexes,
  ...recoveryCodeValuesHistoryTableIndexes,
  ...recoveryCodesTableIndexes,
  ...recoveryCodesHistoryTableIndexes,
  ...recoveryCodesItemsTableIndexes,
  ...sshKeyHistoryTableIndexes,
  ...sshKeyItemsTableIndexes,
  ...categoriesTableIndexes,
  ...customIconsTableIndexes,
  ...iconRefsTableIndexes,
  ...itemCategoryHistoryTableIndexes,
  ...itemLinkHistoryTableIndexes,
  ...itemLinksTableIndexes,
  ...itemTagsTableIndexes,
  ...storeSettingsTableIndexes,
  ...tagsTableIndexes,
  ...vaultItemTagHistoryTableIndexes,
  ...vaultEventsHistoryTableIndexes,
  ...vaultItemCustomFieldsTableIndexes,
  ...vaultItemCustomFieldsHistoryTableIndexes,
  ...vaultItemsTableIndexes,
  ...vaultSnapshotsHistoryTableIndexes,
  ...wifiHistoryTableIndexes,
  ...wifiItemsTableIndexes,
];

