// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api/crypt_api.dart';
import 'api/crypt_api/types.dart';
import 'api/icon_pack_catalog_api.dart';
import 'api/icon_pack_catalog_api/types.dart';
import 'api/keepass_api.dart';
import 'api/keepass_api/types.dart';
import 'api/logging.dart';
import 'api/simple.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  RustStreamSink<FrbBatchDecryptEvent>
  dco_decode_StreamSink_frb_batch_decrypt_event_Sse(dynamic raw);

  @protected
  RustStreamSink<FrbBatchEncryptEvent>
  dco_decode_StreamSink_frb_batch_encrypt_event_Sse(dynamic raw);

  @protected
  RustStreamSink<FrbDecryptEvent> dco_decode_StreamSink_frb_decrypt_event_Sse(
    dynamic raw,
  );

  @protected
  RustStreamSink<FrbEncryptEvent> dco_decode_StreamSink_frb_encrypt_event_Sse(
    dynamic raw,
  );

  @protected
  RustStreamSink<FrbIconPackImportEvent>
  dco_decode_StreamSink_frb_icon_pack_import_event_Sse(dynamic raw);

  @protected
  RustStreamSink<LogEntry> dco_decode_StreamSink_log_entry_Sse(dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  bool dco_decode_box_autoadd_bool(dynamic raw);

  @protected
  FrbBatchDecryptOptions dco_decode_box_autoadd_frb_batch_decrypt_options(
    dynamic raw,
  );

  @protected
  FrbBatchDecryptResult dco_decode_box_autoadd_frb_batch_decrypt_result(
    dynamic raw,
  );

  @protected
  FrbBatchEncryptOptions dco_decode_box_autoadd_frb_batch_encrypt_options(
    dynamic raw,
  );

  @protected
  FrbBatchEncryptResult dco_decode_box_autoadd_frb_batch_encrypt_result(
    dynamic raw,
  );

  @protected
  FrbDecryptOptions dco_decode_box_autoadd_frb_decrypt_options(dynamic raw);

  @protected
  FrbDecryptResult dco_decode_box_autoadd_frb_decrypt_result(dynamic raw);

  @protected
  FrbEncryptOptions dco_decode_box_autoadd_frb_encrypt_options(dynamic raw);

  @protected
  FrbEncryptResult dco_decode_box_autoadd_frb_encrypt_result(dynamic raw);

  @protected
  FrbIconPackError dco_decode_box_autoadd_frb_icon_pack_error(dynamic raw);

  @protected
  FrbIconPackImportProgress
  dco_decode_box_autoadd_frb_icon_pack_import_progress(dynamic raw);

  @protected
  FrbIconPackSummary dco_decode_box_autoadd_frb_icon_pack_summary(dynamic raw);

  @protected
  FrbKeepassAutoType dco_decode_box_autoadd_frb_keepass_auto_type(dynamic raw);

  @protected
  FrbKeepassExportOptions dco_decode_box_autoadd_frb_keepass_export_options(
    dynamic raw,
  );

  @protected
  FrbKeepassMemoryProtection
  dco_decode_box_autoadd_frb_keepass_memory_protection(dynamic raw);

  @protected
  FrbKeepassOtp dco_decode_box_autoadd_frb_keepass_otp(dynamic raw);

  @protected
  FrbProgressEvent dco_decode_box_autoadd_frb_progress_event(dynamic raw);

  @protected
  int dco_decode_box_autoadd_i_32(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw);

  @protected
  BigInt dco_decode_box_autoadd_u_64(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  FrbBatchDecryptEvent dco_decode_frb_batch_decrypt_event(dynamic raw);

  @protected
  FrbBatchDecryptOptions dco_decode_frb_batch_decrypt_options(dynamic raw);

  @protected
  FrbBatchDecryptResult dco_decode_frb_batch_decrypt_result(dynamic raw);

  @protected
  FrbBatchEncryptEvent dco_decode_frb_batch_encrypt_event(dynamic raw);

  @protected
  FrbBatchEncryptOptions dco_decode_frb_batch_encrypt_options(dynamic raw);

  @protected
  FrbBatchEncryptResult dco_decode_frb_batch_encrypt_result(dynamic raw);

  @protected
  FrbBatchError dco_decode_frb_batch_error(dynamic raw);

  @protected
  FrbChunkSizePreset dco_decode_frb_chunk_size_preset(dynamic raw);

  @protected
  FrbDecryptEvent dco_decode_frb_decrypt_event(dynamic raw);

  @protected
  FrbDecryptOptions dco_decode_frb_decrypt_options(dynamic raw);

  @protected
  FrbDecryptResult dco_decode_frb_decrypt_result(dynamic raw);

  @protected
  FrbDecryptedMetadata dco_decode_frb_decrypted_metadata(dynamic raw);

  @protected
  FrbEncryptEvent dco_decode_frb_encrypt_event(dynamic raw);

  @protected
  FrbEncryptOptions dco_decode_frb_encrypt_options(dynamic raw);

  @protected
  FrbEncryptResult dco_decode_frb_encrypt_result(dynamic raw);

  @protected
  FrbIconPackEntry dco_decode_frb_icon_pack_entry(dynamic raw);

  @protected
  FrbIconPackError dco_decode_frb_icon_pack_error(dynamic raw);

  @protected
  FrbIconPackImportEvent dco_decode_frb_icon_pack_import_event(dynamic raw);

  @protected
  FrbIconPackImportProgress dco_decode_frb_icon_pack_import_progress(
    dynamic raw,
  );

  @protected
  FrbIconPackSummary dco_decode_frb_icon_pack_summary(dynamic raw);

  @protected
  FrbKeepassAttachment dco_decode_frb_keepass_attachment(dynamic raw);

  @protected
  FrbKeepassAutoType dco_decode_frb_keepass_auto_type(dynamic raw);

  @protected
  FrbKeepassAutoTypeAssociation dco_decode_frb_keepass_auto_type_association(
    dynamic raw,
  );

  @protected
  FrbKeepassConfig dco_decode_frb_keepass_config(dynamic raw);

  @protected
  FrbKeepassCustomDataItem dco_decode_frb_keepass_custom_data_item(dynamic raw);

  @protected
  FrbKeepassDatabaseExport dco_decode_frb_keepass_database_export(dynamic raw);

  @protected
  FrbKeepassDeletedObject dco_decode_frb_keepass_deleted_object(dynamic raw);

  @protected
  FrbKeepassEntry dco_decode_frb_keepass_entry(dynamic raw);

  @protected
  FrbKeepassExportOptions dco_decode_frb_keepass_export_options(dynamic raw);

  @protected
  FrbKeepassField dco_decode_frb_keepass_field(dynamic raw);

  @protected
  FrbKeepassGroup dco_decode_frb_keepass_group(dynamic raw);

  @protected
  FrbKeepassHistoryEntry dco_decode_frb_keepass_history_entry(dynamic raw);

  @protected
  FrbKeepassMemoryProtection dco_decode_frb_keepass_memory_protection(
    dynamic raw,
  );

  @protected
  FrbKeepassMeta dco_decode_frb_keepass_meta(dynamic raw);

  @protected
  FrbKeepassOtp dco_decode_frb_keepass_otp(dynamic raw);

  @protected
  FrbKeepassTimes dco_decode_frb_keepass_times(dynamic raw);

  @protected
  FrbKeyValue dco_decode_frb_key_value(dynamic raw);

  @protected
  FrbProgressEvent dco_decode_frb_progress_event(dynamic raw);

  @protected
  FrbProgressStage dco_decode_frb_progress_stage(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<FrbBatchError> dco_decode_list_frb_batch_error(dynamic raw);

  @protected
  List<FrbDecryptResult> dco_decode_list_frb_decrypt_result(dynamic raw);

  @protected
  List<FrbEncryptResult> dco_decode_list_frb_encrypt_result(dynamic raw);

  @protected
  List<FrbIconPackEntry> dco_decode_list_frb_icon_pack_entry(dynamic raw);

  @protected
  List<FrbIconPackSummary> dco_decode_list_frb_icon_pack_summary(dynamic raw);

  @protected
  List<FrbKeepassAttachment> dco_decode_list_frb_keepass_attachment(
    dynamic raw,
  );

  @protected
  List<FrbKeepassAutoTypeAssociation>
  dco_decode_list_frb_keepass_auto_type_association(dynamic raw);

  @protected
  List<FrbKeepassCustomDataItem> dco_decode_list_frb_keepass_custom_data_item(
    dynamic raw,
  );

  @protected
  List<FrbKeepassDeletedObject> dco_decode_list_frb_keepass_deleted_object(
    dynamic raw,
  );

  @protected
  List<FrbKeepassEntry> dco_decode_list_frb_keepass_entry(dynamic raw);

  @protected
  List<FrbKeepassField> dco_decode_list_frb_keepass_field(dynamic raw);

  @protected
  List<FrbKeepassGroup> dco_decode_list_frb_keepass_group(dynamic raw);

  @protected
  List<FrbKeepassHistoryEntry> dco_decode_list_frb_keepass_history_entry(
    dynamic raw,
  );

  @protected
  List<FrbKeyValue> dco_decode_list_frb_key_value(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  LogEntry dco_decode_log_entry(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  bool? dco_decode_opt_box_autoadd_bool(dynamic raw);

  @protected
  FrbKeepassAutoType? dco_decode_opt_box_autoadd_frb_keepass_auto_type(
    dynamic raw,
  );

  @protected
  FrbKeepassMemoryProtection?
  dco_decode_opt_box_autoadd_frb_keepass_memory_protection(dynamic raw);

  @protected
  FrbKeepassOtp? dco_decode_opt_box_autoadd_frb_keepass_otp(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_i_32(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw);

  @protected
  BigInt? dco_decode_opt_box_autoadd_u_64(dynamic raw);

  @protected
  Uint8List? dco_decode_opt_list_prim_u_8_strict(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  RustStreamSink<FrbBatchDecryptEvent>
  sse_decode_StreamSink_frb_batch_decrypt_event_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<FrbBatchEncryptEvent>
  sse_decode_StreamSink_frb_batch_encrypt_event_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<FrbDecryptEvent> sse_decode_StreamSink_frb_decrypt_event_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<FrbEncryptEvent> sse_decode_StreamSink_frb_encrypt_event_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<FrbIconPackImportEvent>
  sse_decode_StreamSink_frb_icon_pack_import_event_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<LogEntry> sse_decode_StreamSink_log_entry_Sse(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  bool sse_decode_box_autoadd_bool(SseDeserializer deserializer);

  @protected
  FrbBatchDecryptOptions sse_decode_box_autoadd_frb_batch_decrypt_options(
    SseDeserializer deserializer,
  );

  @protected
  FrbBatchDecryptResult sse_decode_box_autoadd_frb_batch_decrypt_result(
    SseDeserializer deserializer,
  );

  @protected
  FrbBatchEncryptOptions sse_decode_box_autoadd_frb_batch_encrypt_options(
    SseDeserializer deserializer,
  );

  @protected
  FrbBatchEncryptResult sse_decode_box_autoadd_frb_batch_encrypt_result(
    SseDeserializer deserializer,
  );

  @protected
  FrbDecryptOptions sse_decode_box_autoadd_frb_decrypt_options(
    SseDeserializer deserializer,
  );

  @protected
  FrbDecryptResult sse_decode_box_autoadd_frb_decrypt_result(
    SseDeserializer deserializer,
  );

  @protected
  FrbEncryptOptions sse_decode_box_autoadd_frb_encrypt_options(
    SseDeserializer deserializer,
  );

  @protected
  FrbEncryptResult sse_decode_box_autoadd_frb_encrypt_result(
    SseDeserializer deserializer,
  );

  @protected
  FrbIconPackError sse_decode_box_autoadd_frb_icon_pack_error(
    SseDeserializer deserializer,
  );

  @protected
  FrbIconPackImportProgress
  sse_decode_box_autoadd_frb_icon_pack_import_progress(
    SseDeserializer deserializer,
  );

  @protected
  FrbIconPackSummary sse_decode_box_autoadd_frb_icon_pack_summary(
    SseDeserializer deserializer,
  );

  @protected
  FrbKeepassAutoType sse_decode_box_autoadd_frb_keepass_auto_type(
    SseDeserializer deserializer,
  );

  @protected
  FrbKeepassExportOptions sse_decode_box_autoadd_frb_keepass_export_options(
    SseDeserializer deserializer,
  );

  @protected
  FrbKeepassMemoryProtection
  sse_decode_box_autoadd_frb_keepass_memory_protection(
    SseDeserializer deserializer,
  );

  @protected
  FrbKeepassOtp sse_decode_box_autoadd_frb_keepass_otp(
    SseDeserializer deserializer,
  );

  @protected
  FrbProgressEvent sse_decode_box_autoadd_frb_progress_event(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_box_autoadd_i_32(SseDeserializer deserializer);

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  FrbBatchDecryptEvent sse_decode_frb_batch_decrypt_event(
    SseDeserializer deserializer,
  );

  @protected
  FrbBatchDecryptOptions sse_decode_frb_batch_decrypt_options(
    SseDeserializer deserializer,
  );

  @protected
  FrbBatchDecryptResult sse_decode_frb_batch_decrypt_result(
    SseDeserializer deserializer,
  );

  @protected
  FrbBatchEncryptEvent sse_decode_frb_batch_encrypt_event(
    SseDeserializer deserializer,
  );

  @protected
  FrbBatchEncryptOptions sse_decode_frb_batch_encrypt_options(
    SseDeserializer deserializer,
  );

  @protected
  FrbBatchEncryptResult sse_decode_frb_batch_encrypt_result(
    SseDeserializer deserializer,
  );

  @protected
  FrbBatchError sse_decode_frb_batch_error(SseDeserializer deserializer);

  @protected
  FrbChunkSizePreset sse_decode_frb_chunk_size_preset(
    SseDeserializer deserializer,
  );

  @protected
  FrbDecryptEvent sse_decode_frb_decrypt_event(SseDeserializer deserializer);

  @protected
  FrbDecryptOptions sse_decode_frb_decrypt_options(
    SseDeserializer deserializer,
  );

  @protected
  FrbDecryptResult sse_decode_frb_decrypt_result(SseDeserializer deserializer);

  @protected
  FrbDecryptedMetadata sse_decode_frb_decrypted_metadata(
    SseDeserializer deserializer,
  );

  @protected
  FrbEncryptEvent sse_decode_frb_encrypt_event(SseDeserializer deserializer);

  @protected
  FrbEncryptOptions sse_decode_frb_encrypt_options(
    SseDeserializer deserializer,
  );

  @protected
  FrbEncryptResult sse_decode_frb_encrypt_result(SseDeserializer deserializer);

  @protected
  FrbIconPackEntry sse_decode_frb_icon_pack_entry(SseDeserializer deserializer);

  @protected
  FrbIconPackError sse_decode_frb_icon_pack_error(SseDeserializer deserializer);

  @protected
  FrbIconPackImportEvent sse_decode_frb_icon_pack_import_event(
    SseDeserializer deserializer,
  );

  @protected
  FrbIconPackImportProgress sse_decode_frb_icon_pack_import_progress(
    SseDeserializer deserializer,
  );

  @protected
  FrbIconPackSummary sse_decode_frb_icon_pack_summary(
    SseDeserializer deserializer,
  );

  @protected
  FrbKeepassAttachment sse_decode_frb_keepass_attachment(
    SseDeserializer deserializer,
  );

  @protected
  FrbKeepassAutoType sse_decode_frb_keepass_auto_type(
    SseDeserializer deserializer,
  );

  @protected
  FrbKeepassAutoTypeAssociation sse_decode_frb_keepass_auto_type_association(
    SseDeserializer deserializer,
  );

  @protected
  FrbKeepassConfig sse_decode_frb_keepass_config(SseDeserializer deserializer);

  @protected
  FrbKeepassCustomDataItem sse_decode_frb_keepass_custom_data_item(
    SseDeserializer deserializer,
  );

  @protected
  FrbKeepassDatabaseExport sse_decode_frb_keepass_database_export(
    SseDeserializer deserializer,
  );

  @protected
  FrbKeepassDeletedObject sse_decode_frb_keepass_deleted_object(
    SseDeserializer deserializer,
  );

  @protected
  FrbKeepassEntry sse_decode_frb_keepass_entry(SseDeserializer deserializer);

  @protected
  FrbKeepassExportOptions sse_decode_frb_keepass_export_options(
    SseDeserializer deserializer,
  );

  @protected
  FrbKeepassField sse_decode_frb_keepass_field(SseDeserializer deserializer);

  @protected
  FrbKeepassGroup sse_decode_frb_keepass_group(SseDeserializer deserializer);

  @protected
  FrbKeepassHistoryEntry sse_decode_frb_keepass_history_entry(
    SseDeserializer deserializer,
  );

  @protected
  FrbKeepassMemoryProtection sse_decode_frb_keepass_memory_protection(
    SseDeserializer deserializer,
  );

  @protected
  FrbKeepassMeta sse_decode_frb_keepass_meta(SseDeserializer deserializer);

  @protected
  FrbKeepassOtp sse_decode_frb_keepass_otp(SseDeserializer deserializer);

  @protected
  FrbKeepassTimes sse_decode_frb_keepass_times(SseDeserializer deserializer);

  @protected
  FrbKeyValue sse_decode_frb_key_value(SseDeserializer deserializer);

  @protected
  FrbProgressEvent sse_decode_frb_progress_event(SseDeserializer deserializer);

  @protected
  FrbProgressStage sse_decode_frb_progress_stage(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<FrbBatchError> sse_decode_list_frb_batch_error(
    SseDeserializer deserializer,
  );

  @protected
  List<FrbDecryptResult> sse_decode_list_frb_decrypt_result(
    SseDeserializer deserializer,
  );

  @protected
  List<FrbEncryptResult> sse_decode_list_frb_encrypt_result(
    SseDeserializer deserializer,
  );

  @protected
  List<FrbIconPackEntry> sse_decode_list_frb_icon_pack_entry(
    SseDeserializer deserializer,
  );

  @protected
  List<FrbIconPackSummary> sse_decode_list_frb_icon_pack_summary(
    SseDeserializer deserializer,
  );

  @protected
  List<FrbKeepassAttachment> sse_decode_list_frb_keepass_attachment(
    SseDeserializer deserializer,
  );

  @protected
  List<FrbKeepassAutoTypeAssociation>
  sse_decode_list_frb_keepass_auto_type_association(
    SseDeserializer deserializer,
  );

  @protected
  List<FrbKeepassCustomDataItem> sse_decode_list_frb_keepass_custom_data_item(
    SseDeserializer deserializer,
  );

  @protected
  List<FrbKeepassDeletedObject> sse_decode_list_frb_keepass_deleted_object(
    SseDeserializer deserializer,
  );

  @protected
  List<FrbKeepassEntry> sse_decode_list_frb_keepass_entry(
    SseDeserializer deserializer,
  );

  @protected
  List<FrbKeepassField> sse_decode_list_frb_keepass_field(
    SseDeserializer deserializer,
  );

  @protected
  List<FrbKeepassGroup> sse_decode_list_frb_keepass_group(
    SseDeserializer deserializer,
  );

  @protected
  List<FrbKeepassHistoryEntry> sse_decode_list_frb_keepass_history_entry(
    SseDeserializer deserializer,
  );

  @protected
  List<FrbKeyValue> sse_decode_list_frb_key_value(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  LogEntry sse_decode_log_entry(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  bool? sse_decode_opt_box_autoadd_bool(SseDeserializer deserializer);

  @protected
  FrbKeepassAutoType? sse_decode_opt_box_autoadd_frb_keepass_auto_type(
    SseDeserializer deserializer,
  );

  @protected
  FrbKeepassMemoryProtection?
  sse_decode_opt_box_autoadd_frb_keepass_memory_protection(
    SseDeserializer deserializer,
  );

  @protected
  FrbKeepassOtp? sse_decode_opt_box_autoadd_frb_keepass_otp(
    SseDeserializer deserializer,
  );

  @protected
  int? sse_decode_opt_box_autoadd_i_32(SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  BigInt? sse_decode_opt_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  Uint8List? sse_decode_opt_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_frb_batch_decrypt_event_Sse(
    RustStreamSink<FrbBatchDecryptEvent> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_frb_batch_encrypt_event_Sse(
    RustStreamSink<FrbBatchEncryptEvent> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_frb_decrypt_event_Sse(
    RustStreamSink<FrbDecryptEvent> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_frb_encrypt_event_Sse(
    RustStreamSink<FrbEncryptEvent> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_frb_icon_pack_import_event_Sse(
    RustStreamSink<FrbIconPackImportEvent> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_log_entry_Sse(
    RustStreamSink<LogEntry> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_frb_batch_decrypt_options(
    FrbBatchDecryptOptions self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_frb_batch_decrypt_result(
    FrbBatchDecryptResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_frb_batch_encrypt_options(
    FrbBatchEncryptOptions self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_frb_batch_encrypt_result(
    FrbBatchEncryptResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_frb_decrypt_options(
    FrbDecryptOptions self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_frb_decrypt_result(
    FrbDecryptResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_frb_encrypt_options(
    FrbEncryptOptions self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_frb_encrypt_result(
    FrbEncryptResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_frb_icon_pack_error(
    FrbIconPackError self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_frb_icon_pack_import_progress(
    FrbIconPackImportProgress self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_frb_icon_pack_summary(
    FrbIconPackSummary self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_frb_keepass_auto_type(
    FrbKeepassAutoType self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_frb_keepass_export_options(
    FrbKeepassExportOptions self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_frb_keepass_memory_protection(
    FrbKeepassMemoryProtection self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_frb_keepass_otp(
    FrbKeepassOtp self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_frb_progress_event(
    FrbProgressEvent self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_frb_batch_decrypt_event(
    FrbBatchDecryptEvent self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_frb_batch_decrypt_options(
    FrbBatchDecryptOptions self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_frb_batch_decrypt_result(
    FrbBatchDecryptResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_frb_batch_encrypt_event(
    FrbBatchEncryptEvent self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_frb_batch_encrypt_options(
    FrbBatchEncryptOptions self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_frb_batch_encrypt_result(
    FrbBatchEncryptResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_frb_batch_error(FrbBatchError self, SseSerializer serializer);

  @protected
  void sse_encode_frb_chunk_size_preset(
    FrbChunkSizePreset self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_frb_decrypt_event(
    FrbDecryptEvent self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_frb_decrypt_options(
    FrbDecryptOptions self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_frb_decrypt_result(
    FrbDecryptResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_frb_decrypted_metadata(
    FrbDecryptedMetadata self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_frb_encrypt_event(
    FrbEncryptEvent self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_frb_encrypt_options(
    FrbEncryptOptions self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_frb_encrypt_result(
    FrbEncryptResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_frb_icon_pack_entry(
    FrbIconPackEntry self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_frb_icon_pack_error(
    FrbIconPackError self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_frb_icon_pack_import_event(
    FrbIconPackImportEvent self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_frb_icon_pack_import_progress(
    FrbIconPackImportProgress self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_frb_icon_pack_summary(
    FrbIconPackSummary self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_frb_keepass_attachment(
    FrbKeepassAttachment self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_frb_keepass_auto_type(
    FrbKeepassAutoType self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_frb_keepass_auto_type_association(
    FrbKeepassAutoTypeAssociation self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_frb_keepass_config(
    FrbKeepassConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_frb_keepass_custom_data_item(
    FrbKeepassCustomDataItem self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_frb_keepass_database_export(
    FrbKeepassDatabaseExport self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_frb_keepass_deleted_object(
    FrbKeepassDeletedObject self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_frb_keepass_entry(
    FrbKeepassEntry self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_frb_keepass_export_options(
    FrbKeepassExportOptions self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_frb_keepass_field(
    FrbKeepassField self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_frb_keepass_group(
    FrbKeepassGroup self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_frb_keepass_history_entry(
    FrbKeepassHistoryEntry self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_frb_keepass_memory_protection(
    FrbKeepassMemoryProtection self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_frb_keepass_meta(
    FrbKeepassMeta self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_frb_keepass_otp(FrbKeepassOtp self, SseSerializer serializer);

  @protected
  void sse_encode_frb_keepass_times(
    FrbKeepassTimes self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_frb_key_value(FrbKeyValue self, SseSerializer serializer);

  @protected
  void sse_encode_frb_progress_event(
    FrbProgressEvent self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_frb_progress_stage(
    FrbProgressStage self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_frb_batch_error(
    List<FrbBatchError> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_frb_decrypt_result(
    List<FrbDecryptResult> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_frb_encrypt_result(
    List<FrbEncryptResult> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_frb_icon_pack_entry(
    List<FrbIconPackEntry> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_frb_icon_pack_summary(
    List<FrbIconPackSummary> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_frb_keepass_attachment(
    List<FrbKeepassAttachment> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_frb_keepass_auto_type_association(
    List<FrbKeepassAutoTypeAssociation> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_frb_keepass_custom_data_item(
    List<FrbKeepassCustomDataItem> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_frb_keepass_deleted_object(
    List<FrbKeepassDeletedObject> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_frb_keepass_entry(
    List<FrbKeepassEntry> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_frb_keepass_field(
    List<FrbKeepassField> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_frb_keepass_group(
    List<FrbKeepassGroup> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_frb_keepass_history_entry(
    List<FrbKeepassHistoryEntry> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_frb_key_value(
    List<FrbKeyValue> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_log_entry(LogEntry self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_bool(bool? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_frb_keepass_auto_type(
    FrbKeepassAutoType? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_frb_keepass_memory_protection(
    FrbKeepassMemoryProtection? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_frb_keepass_otp(
    FrbKeepassOtp? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_i_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_u_64(BigInt? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_list_prim_u_8_strict(
    Uint8List? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {}
