import '../db_constraint_descriptor.dart';
import '../../tables/vault_items/vault_items.dart';

final Map<String, DbConstraintDescriptor> vaultItemRegistry = {
  VaultItemConstraint.idNotBlank.constraintName: const DbConstraintDescriptor(
    constraint: 'chk_vault_items_id_not_blank',
    entity: 'vaultItem',
    table: 'vault_items',
    field: 'id',
    code: 'vault_item.id.not_blank',
    message: 'ID записи не может быть пустым',
  ),
  VaultItemConstraint.nameNotBlank.constraintName: const DbConstraintDescriptor(
    constraint: 'chk_vault_items_name_not_blank',
    entity: 'vaultItem',
    table: 'vault_items',
    field: 'name',
    code: 'vault_item.name.not_blank',
    message: 'Название записи не может быть пустым',
  ),
  VaultItemConstraint.nameNoOuterWhitespace.constraintName: const DbConstraintDescriptor(
    constraint: 'chk_vault_items_name_no_outer_whitespace',
    entity: 'vaultItem',
    table: 'vault_items',
    field: 'name',
    code: 'vault_item.name.no_outer_whitespace',
    message: 'Название не должно начинаться или заканчиваться пробелами',
  ),
  VaultItemConstraint.descriptionNotBlank.constraintName: const DbConstraintDescriptor(
    constraint: 'chk_vault_items_description_not_blank',
    entity: 'vaultItem',
    table: 'vault_items',
    field: 'description',
    code: 'vault_item.description.not_blank',
    message: 'Описание не может состоять из одних пробелов',
  ),
  VaultItemConstraint.categoryIdNotBlank.constraintName: const DbConstraintDescriptor(
    constraint: 'chk_vault_items_category_id_not_blank',
    entity: 'vaultItem',
    table: 'vault_items',
    field: 'categoryId',
    code: 'vault_item.category_id.not_blank',
    message: 'ID категории не может быть пустым',
  ),
  VaultItemConstraint.iconRefIdNotBlank.constraintName: const DbConstraintDescriptor(
    constraint: 'chk_vault_items_icon_ref_id_not_blank',
    entity: 'vaultItem',
    table: 'vault_items',
    field: 'iconRefId',
    code: 'vault_item.icon_ref_id.not_blank',
    message: 'ID иконки не может быть пустым',
  ),
  VaultItemConstraint.usedCountNonNegative.constraintName: const DbConstraintDescriptor(
    constraint: 'chk_vault_items_used_count_non_negative',
    entity: 'vaultItem',
    table: 'vault_items',
    field: 'usedCount',
    code: 'vault_item.used_count.negative',
    message: 'Счетчик использований не может быть отрицательным',
  ),
  VaultItemConstraint.usedCountLastUsedConsistent.constraintName: const DbConstraintDescriptor(
    constraint: 'chk_vault_items_used_count_last_used_consistent',
    entity: 'vaultItem',
    table: 'vault_items',
    field: 'lastUsedAt',
    code: 'vault_item.used_count.inconsistent',
    message: 'Несоответствие счетчика и даты последнего использования',
  ),
  VaultItemConstraint.recentScoreNonNegative.constraintName: const DbConstraintDescriptor(
    constraint: 'chk_vault_items_recent_score_non_negative',
    entity: 'vaultItem',
    table: 'vault_items',
    field: 'recentScore',
    code: 'vault_item.recent_score.negative',
    message: 'Рейтинг популярности не может быть отрицательным',
  ),
  VaultItemConstraint.archivedAtStateConsistent.constraintName: const DbConstraintDescriptor(
    constraint: 'chk_vault_items_archived_at_state_consistent',
    entity: 'vaultItem',
    table: 'vault_items',
    field: 'archivedAt',
    code: 'vault_item.archived_at.inconsistent',
    message: 'Некорректная дата архивации',
  ),
  VaultItemConstraint.deletedAtStateConsistent.constraintName: const DbConstraintDescriptor(
    constraint: 'chk_vault_items_deleted_at_state_consistent',
    entity: 'vaultItem',
    table: 'vault_items',
    field: 'deletedAt',
    code: 'vault_item.deleted_at.inconsistent',
    message: 'Некорректная дата удаления',
  ),
  VaultItemConstraint.deletedArchivedConflict.constraintName: const DbConstraintDescriptor(
    constraint: 'chk_vault_items_deleted_archived_conflict',
    entity: 'vaultItem',
    table: 'vault_items',
    field: 'isDeleted',
    code: 'vault_item.deleted_archived.conflict',
    message: 'Запись не может быть одновременно удалена и архивирована',
  ),
  VaultItemConstraint.deletedPinnedConflict.constraintName: const DbConstraintDescriptor(
    constraint: 'chk_vault_items_deleted_pinned_conflict',
    entity: 'vaultItem',
    table: 'vault_items',
    field: 'isPinned',
    code: 'vault_item.deleted_pinned.conflict',
    message: 'Удаленная запись не может быть закреплена',
  ),
  VaultItemConstraint.deletedFavoriteConflict.constraintName: const DbConstraintDescriptor(
    constraint: 'chk_vault_items_deleted_favorite_conflict',
    entity: 'vaultItem',
    table: 'vault_items',
    field: 'isFavorite',
    code: 'vault_item.deleted_favorite.conflict',
    message: 'Удаленная запись не может быть в избранном',
  ),
};
