// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'types.freezed.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `EntryFile`, `ImportCandidateSource`, `ImportCandidate`, `ManifestFile`, `ResolvedPackName`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

class FrbIconPackEntry {
  final String key;
  final String packKey;
  final String packName;
  final String iconKey;
  final String name;
  final String relativePath;
  final String svgPath;
  final PlatformInt64 importedAtMillis;

  const FrbIconPackEntry({
    required this.key,
    required this.packKey,
    required this.packName,
    required this.iconKey,
    required this.name,
    required this.relativePath,
    required this.svgPath,
    required this.importedAtMillis,
  });

  @override
  int get hashCode =>
      key.hashCode ^
      packKey.hashCode ^
      packName.hashCode ^
      iconKey.hashCode ^
      name.hashCode ^
      relativePath.hashCode ^
      svgPath.hashCode ^
      importedAtMillis.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FrbIconPackEntry &&
          runtimeType == other.runtimeType &&
          key == other.key &&
          packKey == other.packKey &&
          packName == other.packName &&
          iconKey == other.iconKey &&
          name == other.name &&
          relativePath == other.relativePath &&
          svgPath == other.svgPath &&
          importedAtMillis == other.importedAtMillis;
}

class FrbIconPackError {
  final String code;
  final String message;

  const FrbIconPackError({required this.code, required this.message});

  @override
  int get hashCode => code.hashCode ^ message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FrbIconPackError &&
          runtimeType == other.runtimeType &&
          code == other.code &&
          message == other.message;
}

@freezed
sealed class FrbIconPackImportEvent with _$FrbIconPackImportEvent {
  const FrbIconPackImportEvent._();

  const factory FrbIconPackImportEvent.progress(
    FrbIconPackImportProgress field0,
  ) = FrbIconPackImportEvent_Progress;
  const factory FrbIconPackImportEvent.done(FrbIconPackSummary field0) =
      FrbIconPackImportEvent_Done;
  const factory FrbIconPackImportEvent.error(FrbIconPackError field0) =
      FrbIconPackImportEvent_Error;
}

class FrbIconPackImportProgress {
  final int current;
  final int total;
  final String currentFile;

  const FrbIconPackImportProgress({
    required this.current,
    required this.total,
    required this.currentFile,
  });

  @override
  int get hashCode => current.hashCode ^ total.hashCode ^ currentFile.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FrbIconPackImportProgress &&
          runtimeType == other.runtimeType &&
          current == other.current &&
          total == other.total &&
          currentFile == other.currentFile;
}

class FrbIconPackSummary {
  final String packKey;
  final String displayName;
  final String sourceArchiveName;
  final PlatformInt64 importedAtMillis;
  final int iconCount;

  const FrbIconPackSummary({
    required this.packKey,
    required this.displayName,
    required this.sourceArchiveName,
    required this.importedAtMillis,
    required this.iconCount,
  });

  @override
  int get hashCode =>
      packKey.hashCode ^
      displayName.hashCode ^
      sourceArchiveName.hashCode ^
      importedAtMillis.hashCode ^
      iconCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FrbIconPackSummary &&
          runtimeType == other.runtimeType &&
          packKey == other.packKey &&
          displayName == other.displayName &&
          sourceArchiveName == other.sourceArchiveName &&
          importedAtMillis == other.importedAtMillis &&
          iconCount == other.iconCount;
}
