# The value of AppId uniquely identifies this application.
# Do not use the same AppId value in installers for other applications.
app_id: 20382464-8D3E-41C3-8D04-6292BCFE2C26
publisher: Vartec
publisher_url: https://github.com/leanflutter/fastforge
display_name: Hoplixi
create_desktop_icon: true
# See: https://jrsoftware.org/ishelp/index.php?topic=setup_defaultdirname
# install_dir_name: "D:\\HELLO-WORLD"
# This path is relative to the root directory of your project; The format of icon file must be ico, can not be png or others
# setup_icon_file: windows\runner\resources\app_icon.ico
locales:
  - en
  - ru